// const chunk = (arr, size) =>  feetArrayArray.reduce((acc, e, i) => (i % size ? acc[acc.length - 1].push(e) : acc.push([e]), acc), []);

// // Examples
// chunk([1, 2, 3, 4, 5, 6, 7, 8], 3);     // [[1, 2, 3], [4, 5, 6], [7, 8]]
// chunk([1, 2, 3, 4, 5, 6, 7, 8], 4); 

const  k2FlexKeelhydraMulti = [
    {
        "valAssign":"AVFOOT",
        "manufacturer": "Blatchford",
        "name": "Avalon",
        "lcode1": "L5968",
        "lcode2": "L5972",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "AV-FOOT",
        "cost": "1353.19",
        "reimbursement": "4046",
        "percent": "33%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/avalon.jpg"
      },
      {
        "valAssign":"OK2KIT",
        "manufacturer": "College_Park",
        "name": "Odyssey K2 Foot",
        "lcode1": "L5968",
        "lcode2": "L5972",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "OK2-KIT",
        "cost": "1113",
        "reimbursement": "4046",
        "percent": "28%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/odyssey_k2.jpg"
      },
      {
        "valAssign":"K2DFOOT",
        "manufacturer": "Ossur",
        "name": "K2 Sensation with D/P Ankle",
        "lcode1": "L5968",
        "lcode2": "L5972",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "K2D-FOOT",
        "cost": "1232.57",
        "reimbursement": "4046",
        "percent": "30%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/k2_sensation_ankle.jpg"
      },
      {
        "valAssign":"VS4KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Kintrol",
        "lcode1": "L5968",
        "lcode2": "L5972",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "VS4-KIT",
        "cost": "1272",
        "reimbursement": "4046",
        "percent": "31%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/kintrol.jpg"
      },

]

const  k3FlexHydrauMulti = [

    {
        "valAssign":"ECSTKIT",
        "manufacturer": "Blatchford",
        "name": "Echelon",
        "lcode1": "L5968",
        "lcode2": "L5981",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "EC-ST-KIT",
        "cost": "1883.36",
        "reimbursement": "6657",
        "percent": "28%",
        "pdac": "1/1/2011",
        "image": "../images/echelon_basic.jpg"
      },
      {
        "valAssign":"ODK3KIT",
        "manufacturer": "College_Park",
        "name": "Odyssey K3",
        "lcode1": "L5968",
        "lcode2": "L5981",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "ODK3-KIT",
        "cost": "1589.99",
        "reimbursement": "6657",
        "percent": "24%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/odyssey_k3.jpg"
      },
      {
        "valAssign":"ROMKIT",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "Kinterra",
        "lcode1": "L5968",
        "lcode2": "L5981",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "ROM-KIT",
        "cost": "1861.36",
        "reimbursement": "6657",
        "percent": "28%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/kinterra.jpg"
      },
      {
        "valAssign":"ECERFOOT",
        "manufacturer": "Blatchford",
        "name": "EchelonER",
        "lcode1": "L5968",
        "lcode2": "L5981",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "ECER-FOOT",
        "cost": "2169.72",
        "reimbursement": "6657",
        "percent": "33%",
        "pdac": "1/1/2011",
        "image": "../images/echelon_er.jpg"
      },


]

const K3FlexHydrauMultiVertShock = [


      {
        "valAssign":"ECVTLKIT",
        "manufacturer": "Blatchford",
        "name": "Echelon VT",
        "lcode1": "L5968",
        "lcode2": "L5981",
        "lcode3": "L5988",
        "lcode4": "",
        "hdcode": "ECVT-L-KIT",
        "cost": "3216.57",
        "reimbursement": "8673",
        "percent": "37%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/echelon_vt.jpg"
      },



]

const  SACH = [


    {
        "valAssign":"SCH11XFOOT",
        "manufacturer": "Trulife",
        "name": "Seattle Sach",
        "lcode1": "L5971",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SCH11x-FOOT",
        "cost": "82.04",
        "reimbursement": "203",
        "percent": "40%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/seattle_sach_light.jpg"
      },
      {
        "valAssign":"SFPFOOT",
        "manufacturer": "WillowWood",
        "name": "Sach Foot (SFP)",
        "lcode1": "L5971",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SFP-FOOT",
        "cost": "88.99",
        "reimbursement": "203",
        "percent": "44%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/ww_sach.jpg"
      },




]

const  K2FlexHeel = [


    {
        "valAssign":"SNF16XFOOT",
        "manufacturer": "Trulife",
        "name": "Seattle Natural",
        "lcode1": "L5972",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SNF16x-FOOT",
        "cost": "113.84",
        "reimbursement": "379",
        "percent": "30%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/seattle_sach_light.jpg"
      },
      {
        "valAssign":"BEFOOTKIT",
        "manufacturer": "College_Park",
        "name": "Breeze",
        "lcode1": "L5972",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "BE-FOOT-KIT",
        "cost": "100.17",
        "reimbursement": "379",
        "percent": "26%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/breeze.jpg"
      },
      {
        "valAssign":"STELLARKIT",
        "manufacturer": "Blatchford",
        "name": "Stellar",
        "lcode1": "L5972",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "STELLAR-KIT",
        "cost": "117.62",
        "reimbursement": "379",
        "percent": "31%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/stellar.jpg"
      },
      {
        "valAssign":"TOFOOTKIT",
        "manufacturer": "College_Park",
        "name": "Tempo",
        "lcode1": "L5972",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "TO-FOOT-KIT",
        "cost": "137.27",
        "reimbursement": "379",
        "percent": "36%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/tempo.jpg"
      },
      {
        "valAssign":"1A200FOOTKIT",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "Gery",
        "lcode1": "L5972",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1A200-FOOT-KIT",
        "cost": "162.11",
        "reimbursement": "379",
        "percent": "43%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/gery.jpg"
      },
      {
        "valAssign":"K1A",
        "manufacturer": "Dycor",
        "name": "K1A",
        "lcode1": "L5972",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "K1A",
        "cost": "167.48",
        "reimbursement": "379",
        "percent": "44%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/k1a.jpg"
      },
      {
        "valAssign":"K3U",
        "manufacturer": "Dycor",
        "name": "K3U",
        "lcode1": "L5972",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "K3U",
        "cost": "167.48",
        "reimbursement": "379",
        "percent": "44%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/k1a.jpg"
      },
      {
        "valAssign":"K2PFOOT",
        "manufacturer": "Ossur",
        "name": "K2 Sensation",
        "lcode1": "L5972",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "K2P-FOOT",
        "cost": "206.17",
        "reimbursement": "379",
        "percent": "54%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/k2sensation.jpg"
      },
      {
        "valAssign":"VS5FOOT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Restore",
        "lcode1": "L5972",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "VS5-FOOT",
        "cost": "215.57",
        "reimbursement": "379",
        "percent": "57%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/restore.jpg"
      },
      {
        "valAssign":"1D10",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1D10 Dynamic",
        "lcode1": "L5972",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1D10",
        "cost": "221.38",
        "reimbursement": "379",
        "percent": "58%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/1d10.jpg"
      },
      {
        "valAssign":"DWF",
        "manufacturer": "WillowWood",
        "name": "Durawalk",
        "lcode1": "L5972",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "DWF",
        "cost": "251.91",
        "reimbursement": "379",
        "percent": "67%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/durawalk.jpg",
        "link": "https://www.spsco.com/dynamic-foot-w-toes.html"
      },

      {
        "valAssign":"134KIT",
        "manufacturer": "Fillauer",
        "name": "K2",
        "lcode1": "L5972",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "134-KIT",
        "cost": "307.67",
        "reimbursement": "379",
        "percent": "81%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/134.jpg",
        "link": "https://www.spsco.com/k2-foot.html"
      },
      {
        "valAssign":"1C11",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Terion",
        "lcode1": "L5972",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1C11",
        "cost": "307.98",
        "reimbursement": "379",
        "percent": "81%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/1c11.jpg",
        "link":"https://www.spsco.com/terion-k2.html"
      },
      {
        "valAssign":"1A101FOOT",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "1A101 Dynamic",
        "lcode1": "L5972",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1A101-FOOT",
        "cost": "318.89",
        "reimbursement": "379",
        "percent": "84%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/1a101.jpg",
"link":"https://www.spsco.com/dynastep.html"
      },
      {
        "valAssign":"1M10",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1M10",
        "lcode1": "L5972",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1M10",
        "cost": "340.58",
        "reimbursement": "379",
        "percent": "90%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/1m10.jpg",
"link":"https://www.spsco.com/adjust-multiaxial-foot-w-footshell.html"
      },
      {
        "valAssign":"BSP0FOOT",
        "manufacturer": "Ossur",
        "name": "Balance S",
        "lcode1": "L5972",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "BSP0-FOOT",
        "cost": "356.96",
        "reimbursement": "379",
        "percent": "94%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/bsp0.jpg",
"link":"https://www.spsco.com/balance-foot-s-coming-soon.html"
      },



]

const  K2FlexKeelMultiAxialRot = [

    {
        "valAssign":"SKF20XFOOT",
        "manufacturer": "Trulife",
        "name": "Kinetic",
        "lcode1": "L5972",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SKF20x-FOOT",
        "cost": "291.92",
        "reimbursement": "1011",
        "percent": "29%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/kinetic.jpg",
"link":"https://www.spsco.com/seattle-kinetic-foot-with-pylon.html"
      },
      {
        "valAssign":"CSXKIT",
        "manufacturer": "College_Park",
        "name": "Celsus",
        "lcode1": "L5972",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "CSX-KIT",
        "cost": "261.13",
        "reimbursement": "1011",
        "percent": "26%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/celsus.jpg",
"link":"https://www.spsco.com/celsus-k1-k2-foot.html"
      },
      {
        "valAssign":"SKF10XFOOT",
        "manufacturer": "Trulife",
        "name": "Seattle Kinetic Lightfoot",
        "lcode1": "L5972",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SKF10x-FOOT",
        "cost": "291.92",
        "reimbursement": "1011",
        "percent": "29%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/seattle_kin_lightfoot.jpg",
"link":"https://www.spsco.com/seattle-kinetic-light.html"
      },
      {
        "valAssign":"NAVFOOT",
        "manufacturer": "Blatchford",
        "name": "Navigator",
        "lcode1": "L5972",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "NAV-FOOT",
        "cost": "303.17",
        "reimbursement": "1011",
        "percent": "30%",
        "pdac": "4/8/2021",
        "image": "../images/navigator.jpg",
"link":"https://www.spsco.com/navigator-foot-1.html"
      },
      {
        "valAssign":"SKF30XFOOT",
        "manufacturer": "Trulife",
        "name": "Kinetic Edge",
        "lcode1": "L5972",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SKF30x-FOOT",
        "cost": "291.92",
        "reimbursement": "1011",
        "percent": "29%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/kinetic_edge.jpg",
"link":"https://www.spsco.com/trulife-seattle-kinetic-edge-foot.html"
      },
      {
        "valAssign":"5191FOOT",
        "manufacturer": "Blatchford",
        "name": "Multiflex",
        "lcode1": "L5972",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "5191-FOOT",
        "cost": "240.7",
        "reimbursement": "1011",
        "percent": "24%",
        "pdac": "4/21/2021",
        "image": "../images/multiflex.jpg",
"link":"https://www.spsco.com/multiflex-standard.html"
      },
      {
        "valAssign":"AGMFOOT",
        "manufacturer": "Dycor",
        "name": "AGM (multi-axial foot)",
        "lcode1": "L5972",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "AGM-FOOT",
        "cost": "381.05",
        "reimbursement": "1011",
        "percent": "38%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/agm.jpg",
"link":"https://www.spsco.com/dycor-aggressive-gait-management-foot.html"
      },
      {
        "valAssign":"STMFOOT",
        "manufacturer": "Dycor",
        "name": "STM (multi-axial foot)",
        "lcode1": "L5972",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "STM-FOOT",
        "cost": "381.05",
        "reimbursement": "1011",
        "percent": "38%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/stm.jpg",
"link":"https://www.spsco.com/dycor-soft-tissue-management-foot.html"
      },
      {
        "valAssign":"1A30",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1A30 Greissenger Plus",
        "lcode1": "L5972",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1A30",
        "cost": "408.99",
        "reimbursement": "1011",
        "percent": "40%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/1a30.jpg",
"link":"https://www.spsco.com/greissinger-plus-foot.html"
      },


]


const  K2FlexKeelAxialRotVert = [


    {
        "valAssign":"BST0FOOT",
        "manufacturer": "Ossur",
        "name": "Balance S Torsion",
        "lcode1": "L5972",
        "lcode2": "L5984",
        "lcode3": "L5988",
        "lcode4": "",
        "hdcode": "BST0-FOOT",
        "cost": "1550.25",
        "reimbursement": "2972",
        "percent": "52%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/bst0.jpg",
"link":"https://www.spsco.com/balance-foot-s-torsion-coming-soon.html"
      },

]

const  Microprocessor = [

    {
        "valAssign":"ELANICFOOT",
        "manufacturer": "Blatchford",
        "name": "Elan IC",
        "lcode1": "L5973",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "ELANIC-FOOT",
        "cost": "7648.51",
        "reimbursement": "17363",
        "percent": "44%",
        "pdac": "9/18/2020",
        "image": "../images/elan_ic.jpg",
"link":"https://www.spsco.com/elanic-foot.html"
      },
      {
        "valAssign":"ELANFOOT",
        "manufacturer": "Blatchford",
        "name": "Elan MPF",
        "lcode1": "L5973",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "ELAN-FOOT",
        "cost": "7298.1",
        "reimbursement": "17363",
        "percent": "42%",
        "pdac": "1/1/2015",
        "image": "../images/elan.jpg",
"link":"https://www.spsco.com/elan-microprocessor-controlled-foot.html"
      },
      {
        "valAssign":"PSX0FOOT",
        "manufacturer": "Ossur",
        "name": "Proprio MPF",
        "lcode1": "L5973",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "PSX0-FOOT",
        "cost": "7758.83",
        "reimbursement": "17363",
        "percent": "45%",
        "pdac": "1/1/2010",
        "image": "../images/proprio.jpg",
"link":"https://www.spsco.com/proprio-foot.html"
      },
      {
        "valAssign":"F14N2KIT",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "Kinnex MPF",
        "lcode1": "L5973",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "F14-N2-KIT",
        "cost": "8013.23",
        "reimbursement": "17363",
        "percent": "46%",
        "pdac": "11/19/2020",
        "image": "../images/kinnex_mpf.jpg",
        "link":"https://www.spsco.com/kinnex-2-0-1.html"
      },
      {
        "valAssign":"1B1",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1B1 Meridium MPF",
        "lcode1": "L5973",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1B1",
        "cost": "9010",
        "reimbursement": "17363",
        "percent": "52%",
        "pdac": "11/13/2020",
        "image": "../images/meridium.jpg",
"link":"https://www.spsco.com/meridium.html"
      },


]


const  SingAxis = [


    {
        "valAssign":"SAFFOOT",
        "manufacturer": "WillowWood",
        "name": "Single Axis Foot",
        "lcode1": "L5974",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SAF-FOOT",
        "cost": "140.09",
        "reimbursement": "233",
        "percent": "60%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/saf_foot.jpg",
"link":"https://www.spsco.com/endoskeletal-single-axis-ankle-1.html"
      },
      {
        "valAssign":"1H38",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Single Axis",
        "lcode1": "L5974",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1H38",
        "cost": "251.36",
        "reimbursement": "233",
        "percent": "108%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/1h38.jpg",
"link":"https://www.spsco.com/single-axis-foot-only-men-10mm-toes.html"
      },


]


const  EnergyStore = [


    {
        "valAssign":"SLF19XFOOT",
        "manufacturer": "Trulife",
        "name": "Seattle Lightfoot 2",
        "lcode1": "L5976",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SLF19x-FOOT",
        "cost": "279.2",
        "reimbursement": "559",
        "percent": "50%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"LCEFOOT",
        "manufacturer": "Dycor",
        "name": "Chopart/Listfranc Partial Foot",
        "lcode1": "L5976",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "LCE-FOOT",
        "cost": "152.64",
        "reimbursement": "559",
        "percent": "27%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/chopart_lisfranc_foot.jpg",
"link":"https://www.spsco.com/lisfranc-chopart-energy-returning-foot.html"
      },
      {
        "valAssign":"IMPMMLHFOOT",
        "manufacturer": "WillowWood",
        "name": "Impulse",
        "lcode1": "L5976",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "IMPM-MLH-FOOT",
        "cost": "201.09",
        "reimbursement": "559",
        "percent": "36%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/impulse.jpg",
"link":"https://www.spsco.com/impulse-men-s-foot-with-low-heel.html"
      },
      {
        "valAssign":"JBPEFOOT",
        "manufacturer": "Ossur",
        "name": "Balance J",
        "lcode1": "L5976",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "JBPE-FOOT",
        "cost": "266.48",
        "reimbursement": "559",
        "percent": "48%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/balance.jpg",
"link":"https://www.spsco.com/balance-j.html"
      },
      {
        "valAssign":"SEF19XFOOT",
        "manufacturer": "Trulife",
        "name": "Seattle Energy",
        "lcode1": "L5976",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SEF19x-FOOT",
        "cost": "279.2",
        "reimbursement": "559",
        "percent": "50%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/seattle_energy.jpg",
"link":"https://www.spsco.com/seattle-energy-foot.html"
      },
      {
        "valAssign":"SZM45XFOOT",
        "manufacturer": "Trulife",
        "name": "Seattle Zumo",
        "lcode1": "L5976",
        "lcode2": "L5999",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SZM45x-FOOT",
        "cost": "279.2",
        "reimbursement": "559",
        "percent": "50%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/zumo_foot.jpg",
"link":"https://www.spsco.com/seattle-zumo-foot.html"
      },
      {
        "valAssign":"SEF1X",
        "manufacturer": "Trulife",
        "name": "Child’s Play",
        "lcode1": "L5976",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SEF1x",
        "cost": "287.49",
        "reimbursement": "559",
        "percent": "51%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/childs_play.jpg",
"link":"https://www.spsco.com/seattle-childs-play-energy-foot.html"
      },
      {
        "valAssign":"VS1KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Senator",
        "lcode1": "L5976",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "VS1-KIT",
        "cost": "369.57",
        "reimbursement": "559",
        "percent": "66%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/senator.jpg",
"link":"https://www.spsco.com/senator.html"
      },
      {
        "valAssign":"1E80FOOTPLATE",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1E80 Chopart",
        "lcode1": "L5976",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1E80-FOOTPLATE",
        "cost": "527.88",
        "reimbursement": "559",
        "percent": "94%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/1E80_footplate.jpg",
"link":"https://www.spsco.com/chopart-1-01.html"
      },
      {
        "valAssign":"RUSHCHOPART",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "RUSH_Chopart_formerly_RUSH_76",
        "lcode1": "L5976",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "RUSH CHOPART",
        "cost": "580.83",
        "reimbursement": "559",
        "percent": "104%",
        "pdac": "1/1/2017",
        "image": "../images/rush_chopart.jpg",
"link":"https://www.spsco.com/rush-chopart-k3-k4-foot.html"
      },
      {
        "valAssign":"CHPKIT",
        "manufacturer": "Ossur",
        "name": "Chopart Foot/Insert",
        "lcode1": "L5976",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "CHP-KIT",
        "cost": "598.47",
        "reimbursement": "559",
        "percent": "107%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/chp00.jpg",
        "link":"https://www.spsco.com/chopart-foot-kit.html"
      },
      {
        "valAssign":"MHD300KIT",
        "manufacturer": "WillowWood",
        "name": "Magnum Heavy Duty",
        "lcode1": "L5976",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "MHD-300-KIT",
        "cost": "630.7",
        "reimbursement": "559",
        "percent": "113%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/magnum_heavy_duty.jpg",
        "link":"https://www.spsco.com/magnum-heavy-duty-foot-1-01.html"
      },


]


const  MultiAxialDynamResp = [

    {
        "valAssign":"TRIBKIT",
        "manufacturer": "College_Park",
        "name": "Tribute",
        "lcode1": "L5979",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "TRIB-KIT",
        "cost": "317.99",
        "reimbursement": "2277",
        "percent": "14%",
        "pdac": "3/16/2021",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"FBPFOOT",
        "manufacturer": "Ossur",
        "name": "Flex Balance",
        "lcode1": "L5979",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "FBP-FOOT",
        "cost": "247.4",
        "reimbursement": "2277",
        "percent": "11%",
        "pdac": "4/19/2013",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"TPIKIT",
        "manufacturer": "College_Park",
        "name": "Truper",
        "lcode1": "L5979",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "TP-KIT",
        "cost": "409.96",
        "reimbursement": "2277",
        "percent": "18%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1D35",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1D35 Dynamic Motion Foot",
        "lcode1": "L5979",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1D35",
        "cost": "553.81",
        "reimbursement": "2277",
        "percent": "24%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"DR",
        "manufacturer": "Dycor",
        "name": "Dynamic Response",
        "lcode1": "L5979",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "DR",
        "cost": "572.4",
        "reimbursement": "2277",
        "percent": "25%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"TSKIT",
        "manufacturer": "College_Park",
        "name": "Tru Step",
        "lcode1": "L5979",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "TS-KIT",
        "cost": "757.21",
        "reimbursement": "2277",
        "percent": "33%",
        "pdac": "3/24/2021",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"VKIT",
        "manufacturer": "College_Park",
        "name": "Venture",
        "lcode1": "L5979",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "V-KIT",
        "cost": "860.56",
        "reimbursement": "2277",
        "percent": "38%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },


]


const  FlexFoot = [


    {
        "valAssign":"JAVKIT",
        "manufacturer": "Blatchford",
        "name": "Javelin",
        "lcode1": "L5980",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "JAV-KIT",
        "cost": "972.03",
        "reimbursement": "3700",
        "percent": "26%",
        "pdac": "9/10/2020",
        "image": "../images/JavelinFoot.jpg"
      },
      {
        "valAssign":"131KIT",
        "manufacturer": "Fillauer",
        "name": "Aeris Activity",
        "lcode1": "L5980",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "131-KIT",
        "cost": "1095.33",
        "reimbursement": "3700",
        "percent": "30%",
        "pdac": "11/19/2020",
        "image": "../images/Aeris_Foot.jpg"
      },
      {
        "valAssign":"CHX0KIT",
        "manufacturer": "Ossur",
        "name": "Cheetah Xplore Jr",
        "lcode1": "L5980",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "CHX0-KIT",
        "cost": "804.54",
        "reimbursement": "3700",
        "percent": "22%",
        "pdac": "10/17/2020",
        "image": "../images/cheetah_foot_adult.jpg"
      },
      {
        "valAssign":"RS4FOOT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Silhouette",
        "lcode1": "L5980",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "RS4-FOOT",
        "cost": "968.47",
        "reimbursement": "3700",
        "percent": "26%",
        "pdac": "12/24/2020",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"VFMODKIT",
        "manufacturer": "Ossur",
        "name": "Vari-Flex Modular",
        "lcode1": "L5980",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "VFMOD-KIT",
        "cost": "1331.65",
        "reimbursement": "3700",
        "percent": "36%",
        "pdac": "10/17/2020",
        "image": "../images/vari_flex_modular_image.jpg"
      },
      {
        "valAssign":"178KIT",
        "manufacturer": "Fillauer",
        "name": "Formula (adult or pediatric)",
        "lcode1": "L5980",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "178-KIT",
        "cost": "1588.42",
        "reimbursement": "3700",
        "percent": "43%",
        "pdac": "11/13/2020",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"EBSTKIT",
        "manufacturer": "Blatchford",
        "name": "Elite Blade",
        "lcode1": "L5980",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "EB-ST-KIT",
        "cost": "1650.55",
        "reimbursement": "3700",
        "percent": "45%",
        "pdac": "9/9/2020",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"137PMKIT",
        "manufacturer": "Fillauer",
        "name": "All Pro w/ Posterior Mount",
        "lcode1": "L5980",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "137-PM-KIT",
        "cost": "1811.25",
        "reimbursement": "3700",
        "percent": "49%",
        "pdac": "11/19/2020",
        "image": "../images/AllProFoot.jpg"
      },
      {
        "valAssign":"FSX009FOOT",
        "manufacturer": "Ossur",
        "name": "Cheetah Xplore",
        "lcode1": "L5980",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "FSX009-FOOT",
        "cost": "1895.28",
        "reimbursement": "3700",
        "percent": "51%",
        "pdac": "10/17/2020",
        "image": "../images/cheetah_foot_adult.jpg"
      },
      {
        "valAssign":"1E61",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Springlite II (Adult or Child)",
        "lcode1": "L5980",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1E61 or 1E66 - Freeform",
        "cost": "0",
        "reimbursement": "3700",
        "percent": "0%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },


]


const  FlexFootMultiAxialAnkle = [

    {
        "valAssign":"F10KIT",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "DynAdapt",
        "lcode1": "L5980",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "F10-KIT",
        "cost": "849.75",
        "reimbursement": "4333",
        "percent": "20%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"SZN20XFOOT",
        "manufacturer": "Trulife",
        "name": "Seattle Zenith",
        "lcode1": "L5980",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SZN20x-FOOT",
        "cost": "571.76",
        "reimbursement": "4333",
        "percent": "13%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/Zenith.jpg"
      },
      {
        "valAssign":"120XDKIT",
        "manufacturer": "Fillauer",
        "name": "Ibex System",
        "lcode1": "L5980",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "120-XD-KIT",
        "cost": "980.32",
        "reimbursement": "4333",
        "percent": "23%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1E58",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1E58 Axtion DP",
        "lcode1": "L5980",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1E58",
        "cost": "1162.26",
        "reimbursement": "4333",
        "percent": "27%",
        "pdac": "11/19/2020",
        "image": "../images/",
"link":""
      },


]


const  FlexWalk = [


    {
        "valAssign":"FS3KIT",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "FS 3000 (Highlander)",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "FS3-KIT",
        "cost": "662.5",
        "reimbursement": "2989",
        "percent": "22%",
        "pdac": "3/3/2012",
        "image": "../images/Highlander.jpg"
      },
      {
        "valAssign":"123KIT",
        "manufacturer": "Fillauer",
        "name": "Aeris LP",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "123-KIT",
        "cost": "557.38",
        "reimbursement": "2989",
        "percent": "19%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/AerisPerformance.jpg"
      },
      {
        "valAssign":"VJB0KIT",
        "manufacturer": "Ossur",
        "name": "Vari-Flex Junior",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "VJB0-KIT",
        "cost": "599.11",
        "reimbursement": "2989",
        "percent": "20%",
        "pdac": "10/20/2020",
        "image": "../images/vari_flex_junior_image.jpg"
      },
      {
        "valAssign":"DEFKIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Defender Pediatric",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "DEF-KIT",
        "cost": "661.6",
        "reimbursement": "2989",
        "percent": "22%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1C30KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Trias",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1C30-KIT",
        "cost": "689.91",
        "reimbursement": "2989",
        "percent": "23%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1116FOOT",
        "manufacturer": "STG",
        "name": "Endurance",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1116-FOOT",
        "cost": "696.03",
        "reimbursement": "2989",
        "percent": "23%",
        "pdac": "11/19/2020",
        "image": "../images/EnduranceK1K2.jpg"
      },
      {
        "valAssign":"PACKIT",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "FS 2000 (Pacifica)",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "PAC-KIT",
        "cost": "702.33",
        "reimbursement": "2989",
        "percent": "23%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"PACKITTWO",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "FS 4000 (Pacifica Low Profile)",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "PAC-KIT",
        "cost": "702.33",
        "reimbursement": "2989",
        "percent": "23%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"135KIT",
        "manufacturer": "Fillauer",
        "name": "WAVE Comfort 3",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "135-KIT",
        "cost": "709.49",
        "reimbursement": "2989",
        "percent": "24%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"STF19XFOOT",
        "manufacturer": "Trulife",
        "name": "Triumph",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "STF19x-FOOT",
        "cost": "762.56",
        "reimbursement": "2989",
        "percent": "26%",
        "pdac": "4/1/2021",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"RUSHHIPRO",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "RUSH_HiPro_formerly_RUSH_87",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "RUSH HIPRO",
        "cost": "795",
        "reimbursement": "2989",
        "percent": "27%",
        "pdac": "1/1/2017",
        "image": "../images/RushHiPro.jpg"
      },
      {
        "valAssign":"HZKIT",
        "manufacturer": "College_Park",
        "name": "Horizon",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "HZ-KIT",
        "cost": "516.06",
        "reimbursement": "2989",
        "percent": "17%",
        "pdac": "3/16/2021",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"FAFOOT",
        "manufacturer": "Ossur",
        "name": "Assure Foot",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "FA-FOOT",
        "cost": "547.60",
        "reimbursement": "2989",
        "percent": "18%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"SZN10XFOOT",
        "manufacturer": "Trulife",
        "name": "Seattle Zenith LP",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SZN10X-FOOT",
        "cost": "571.76",
        "reimbursement": "2989",
        "percent": "19%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1115FOOT",
        "manufacturer": "STG",
        "name": "Endurance LP",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1115-FOOT",
        "cost": "614.14",
        "reimbursement": "2989",
        "percent": "21%",
        "pdac": "11/19/2020",
        "image": "../images/EnduranceLowProfile.jpg"
      },
      {
        "valAssign":"VS2KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Promenade",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "VS2-KIT",
        "cost": "621.85",
        "reimbursement": "2989",
        "percent": "21%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"ELSTKIT",
        "manufacturer": "Blatchford",
        "name": "Elite 2",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "EL-ST-KIT",
        "cost": "662.5",
        "reimbursement": "2989",
        "percent": "22%",
        "pdac": "9/9/2020",
        "image": "../images/Elite2.jpg"
      },
      {
        "valAssign":"ESPSTFOOTKIT",
        "manufacturer": "Blatchford",
        "name": "Esprit",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "ESP-ST-FOOT-KIT",
        "cost": "669.76",
        "reimbursement": "2989",
        "percent": "22%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"TREKKLP",
        "manufacturer": "MakStride_formerly_BioQuest",
        "name": "Trekk LP",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "TREKK LP",
        "cost": "756.84",
        "reimbursement": "2989",
        "percent": "25%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"SLS49FOOT",
        "manufacturer": "Trulife",
        "name": "Solas",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SLS49-FOOT",
        "cost": "762.56",
        "reimbursement": "2989",
        "percent": "26%",
        "pdac": "7/1/2021",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1E56KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1E56 Axtion",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1E56-KIT",
        "cost": "788.19",
        "reimbursement": "2989",
        "percent": "26%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1C63KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1C63 Triton LP",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1C63-KIT",
        "cost": "798.36",
        "reimbursement": "2989",
        "percent": "27%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/TritonLow.jpg"
      },
      {
        "valAssign":"FS1KIT",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "FS 1000 (Sierra)",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "FS1-KIT",
        "cost": "802.05",
        "reimbursement": "2989",
        "percent": "27%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"LP2KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "LP Symes",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "LP2-KIT",
        "cost": "850.41",
        "reimbursement": "2989",
        "percent": "28%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"F22KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Maverick Comfort AT model",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "F22-KIT",
        "cost": "850.81",
        "reimbursement": "2989",
        "percent": "28%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"122KIT",
        "manufacturer": "Fillauer",
        "name": "Aeris Performance 2",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "122-KIT",
        "cost": "869.02",
        "reimbursement": "2989",
        "percent": "29%",
        "pdac": "11/13/2020",
        "image": "../images/AerisPerformance.jpg"
      },
      {
        "valAssign":"RUSHROVER",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "RUSH_Rover",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "RUSH ROVER",
        "cost": "872.96",
        "reimbursement": "2989",
        "percent": "29%",
        "pdac": "1/1/2017",
        "image": "../images/rush_rover_main.jpg"
      },
      {
        "valAssign":"RUSHKID",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "RUSH_Kid",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "RUSH KID",
        "cost": "872.96",
        "reimbursement": "2989",
        "percent": "29%",
        "pdac": "1/1/2017",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"K001FOOT",
        "manufacturer": "WillowWood",
        "name": "KOA",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "K001-FOOT",
        "cost": "886.69",
        "reimbursement": "2989",
        "percent": "30%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"10010KIT",
        "manufacturer": "Fillauer",
        "name": "Element System",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "100-10-KIT",
        "cost": "891.28",
        "reimbursement": "2989",
        "percent": "30%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"SOKIT",
        "manufacturer": "College_Park",
        "name": "Soleus",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SO-KIT",
        "cost": "932.78",
        "reimbursement": "2989",
        "percent": "31%",
        "pdac": "10/17/2020",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1C60KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1C60 Triton",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1C60-KIT",
        "cost": "956.3",
        "reimbursement": "2989",
        "percent": "32%",
        "pdac": "11/13/2020",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"VFKIT",
        "manufacturer": "Ossur",
        "name": "Vari-Flex",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "VF-KIT",
        "cost": "999.15",
        "reimbursement": "2989",
        "percent": "33%",
        "pdac": "10/20/2020",
        "image": "../images/vari_flex_modular_image.jpg"
      },
      {
        "valAssign":"1E57KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1E57 Lo Rider",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1E57-KIT",
        "cost": "1034.76",
        "reimbursement": "2989",
        "percent": "35%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"PXCOFOOT",
        "manufacturer": "Ossur",
        "name": "Pro-flex XC",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "PXC0-FOOT",
        "cost": "1351.18",
        "reimbursement": "2989",
        "percent": "45%",
        "pdac": "10/20/2020",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"137KIT",
        "manufacturer": "Fillauer",
        "name": "All_Pro_Direct_Mount_Pyramid",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "137-KIT",
        "cost": "1638.37",
        "reimbursement": "2989",
        "percent": "55%",
        "pdac": "10/20/2020",
        "image": "../images/AllProFoot.jpg"
      },
      {
        "valAssign":"SWIMKIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Freestyle (Freedom LP) and Swim Ankle",
        "lcode1": "L5981",
        "lcode2": "L5999",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SWIM-KIT",
        "cost": "1943.67",
        "reimbursement": "#N/A",
        "percent": "#N/A",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"FS3KITTWO",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "Highlander Max",
        "lcode1": "L5981",
        "lcode2": "L5999",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "FS3-KIT",
        "cost": "662.5",
        "reimbursement": "#N/A",
        "percent": "#N/A",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/Highlander.jpg"
      },
      {
        "valAssign":"FS5KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Thrive",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "FS5-KIT",
        "cost": "937.52",
        "reimbursement": "2989",
        "percent": "31%",
        "pdac": "1/1/2012",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1C50KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1C50 Taleo",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1C50-KIT",
        "cost": "966.68",
        "reimbursement": "2989",
        "percent": "32%",
        "pdac": "11/13/2020",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"PLP0FOOT",
        "manufacturer": "Ossur",
        "name": "Pro-flex LP",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "PLP0-FOOT",
        "cost": "983.15",
        "reimbursement": "2989",
        "percent": "33%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1C53FOOT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1C53 Taleo LP",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1C53-FOOT",
        "cost": "1031.13",
        "reimbursement": "2989",
        "percent": "34%",
        "pdac": "11/13/2020",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1C64KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1C64 Triton HD",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1C64-KIT",
        "cost": "1095.51",
        "reimbursement": "2989",
        "percent": "37%",
        "pdac": "11/13/2020",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1A600FOOT",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "DynaTrek",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1A600-FOOT",
        "cost": "1128.38",
        "reimbursement": "2989",
        "percent": "38%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1C40K",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1C40 C-Walk",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1C40=K",
        "cost": "1136.73",
        "reimbursement": "2989",
        "percent": "38%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"FSYMESKIT",
        "manufacturer": "Ossur",
        "name": "Flex Symes",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "FSYMES-KIT",
        "cost": "1167.69",
        "reimbursement": "2989",
        "percent": "39%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"FSX007FOOT",
        "manufacturer": "Ossur",
        "name": "Flex Junior",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "FSX007-FOOT",
        "cost": "1518.13",
        "reimbursement": "2989",
        "percent": "51%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1E95",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1E95 Challenger",
        "lcode1": "L5981",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1E95",
        "cost": "1691.2",
        "reimbursement": "2989",
        "percent": "57%",
        "pdac": "11/18/2020",
        "image": "../images/",
"link":""
      },


]


const  FlexWalkMultiAxial = [


    {
        "valAssign":"EPSTKIT",
        "manufacturer": "Blatchford",
        "name": "Epirus",
        "lcode1": "L5981",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "EP-ST-KIT",
        "cost": "788.62",
        "reimbursement": "3622",
        "percent": "22%",
        "pdac": "4/8/2021",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"RUSHRAMPAGELP",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "RUSH_Rampage_LP_formerly_RUSH_LoPro",
        "lcode1": "L5981",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "RUSH RAMPAGE LP",
        "cost": "795",
        "reimbursement": "3622",
        "percent": "22%",
        "pdac": "1/1/2017",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"VLKIT",
        "manufacturer": "College_Park",
        "name": "Velocity",
        "lcode1": "L5981",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "VL-KIT",
        "cost": "757.21",
        "reimbursement": "3622",
        "percent": "21%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1C58FOOTKIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1C58 Taleo Side Flex",
        "lcode1": "L5981",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1C58-FOOT-KIT",
        "cost": "971.13",
        "reimbursement": "3622",
        "percent": "27%",
        "pdac": "8/25/2021",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"TALUXKIT",
        "manufacturer": "Ossur",
        "name": "Talux",
        "lcode1": "L5981",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "TALUX-KIT",
        "cost": "1002.02",
        "reimbursement": "3622",
        "percent": "28%",
        "pdac": "10/20/2020",
        "image": "../images/Talux.jpg"
      },
      {
        "valAssign":"1C68KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1C68 Triton Side Flex",
        "lcode1": "L5981",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1C68-KIT",
        "cost": "1017.6",
        "reimbursement": "3622",
        "percent": "28%",
        "pdac": "8/25/2021",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"M002FOOTKIT",
        "manufacturer": "WillowWood",
        "name": "Meta Arc",
        "lcode1": "L5981",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "M002-FOOT-KIT",
        "cost": "1038.8",
        "reimbursement": "3622",
        "percent": "29%",
        "pdac": "12/3/2020",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"BXTFOOT",
        "manufacturer": "Blatchford",
        "name": "Blade XT",
        "lcode1": "L5981",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "BXT-FOOT",
        "cost": "1402.17",
        "reimbursement": "3622",
        "percent": "39%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/BladeXT.jpg"
      },
      {
        "valAssign":"PENDING",
        "manufacturer": "College_Park",
        "name": "Terrain",
        "lcode1": "L5981",
        "lcode2": "L5986",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "PENDING",
        "cost": "Pending",
        "reimbursement": "3622",
        "percent": "#VALUE!",
        "pdac": "5/21/2021",
        "image": "../images/",
"link":""
      },

]


const  VertShockAxialRot = [

    {
        "valAssign":"EVTSTKIT",
        "manufacturer": "Blatchford",
        "name": "Elite VT",
        "lcode1": "L5984",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "EVT-ST-KIT",
        "cost": "1666.71",
        "reimbursement": "7829",
        "percent": "21%",
        "pdac": "9/9/2020",
        "image": "../images/EliteBlade.jpg"
      },
      {
        "valAssign":"RUSHROGUE",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "RUSH_Rogue",
        "lcode1": "L5984",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "RUSH ROGUE",
        "cost": "1378",
        "reimbursement": "7829",
        "percent": "18%",
        "pdac": "1/1/2017",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"ROG2",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "RUSH_Rogue_2",
        "lcode1": "L5984",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "ROG2",
        "cost": "1378",
        "reimbursement": "7829",
        "percent": "18%",
        "pdac": "5/14/2021",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"10510KIT",
        "manufacturer": "Fillauer",
        "name": "Element DS System",
        "lcode1": "L5984",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "105-10-KIT",
        "cost": "1573.92",
        "reimbursement": "7829",
        "percent": "20%",
        "pdac": "11/13/2020",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"F20S3KIT",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "Shockwave",
        "lcode1": "L5984",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "F20-S3-KIT",
        "cost": "1671.25",
        "reimbursement": "7829",
        "percent": "21%",
        "pdac": "9/1/2021",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"RFRKIT",
        "manufacturer": "Ossur",
        "name": "Ceterus (Renamed ReFlex Rotate)",
        "lcode1": "L5984",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "RFR-KIT",
        "cost": "1855.21",
        "reimbursement": "7829",
        "percent": "24%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"EBVTSTKIT",
        "manufacturer": "Blatchford",
        "name": "Elite Blade VT",
        "lcode1": "L5984",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "EBVT-ST-KIT",
        "cost": "1921.78",
        "reimbursement": "7829",
        "percent": "25%",
        "pdac": "9/9/2020",
        "image": "../images/EliteBlade.jpg"
      },
      {
        "valAssign":"PXT0FOOT",
        "manufacturer": "Ossur",
        "name": "Pro-flex XC Torsion",
        "lcode1": "L5984",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "PXT0-FOOT",
        "cost": "2586.4",
        "reimbursement": "7829",
        "percent": "33%",
        "pdac": "10/17/2020",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"PLT0FOOT",
        "manufacturer": "Ossur",
        "name": "Pro-flex LP Torsion",
        "lcode1": "L5984",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "PLT0-FOOT",
        "cost": "2153.92",
        "reimbursement": "7829",
        "percent": "28%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },



]


const  VertShockMultiAxialRot = [

    {
        "valAssign":"F15KIT",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "Agilix",
        "lcode1": "L5986",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "F15-KIT",
        "cost": "1027.83",
        "reimbursement": "7892",
        "percent": "13%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"K2CS",
        "manufacturer": "MakStride_formerly_BioQuest",
        "name": "Comfort Stride",
        "lcode1": "L5986",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "K2CS",
        "cost": "550.35",
        "reimbursement": "7892",
        "percent": "7%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"TREKKLP",
        "manufacturer": "MakStride_formerly_BioQuest",
        "name": "Trekk",
        "lcode1": "L5986",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "TREKK LP",
        "cost": "756.84",
        "reimbursement": "7892",
        "percent": "10%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"MX1",
        "manufacturer": "MakStride_formerly_BioQuest",
        "name": "Natural Stride",
        "lcode1": "L5986",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "MX1",
        "cost": "923.05",
        "reimbursement": "7892",
        "percent": "12%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"SOKIT",
        "manufacturer": "College_Park",
        "name": "Tactical",
        "lcode1": "L5986",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "SO-KIT",
        "cost": "932.78",
        "reimbursement": "7892",
        "percent": "12%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"RENATKIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Renegade AT or LP-AT",
        "lcode1": "L5986",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "RENAT-KIT",
        "cost": "937.52",
        "reimbursement": "7892",
        "percent": "12%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"F11KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Maverick Xtreme",
        "lcode1": "L5986",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "F11-KIT",
        "cost": "937.52",
        "reimbursement": "7892",
        "percent": "12%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"F21KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Maverick Xtreme AT",
        "lcode1": "L5986",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "F21-KIT",
        "cost": "937.52",
        "reimbursement": "7892",
        "percent": "12%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"MX3",
        "manufacturer": "MakStride_formerly_BioQuest",
        "name": "Ultra Stride",
        "lcode1": "L5986",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "MX3",
        "cost": "996.4",
        "reimbursement": "7892",
        "percent": "13%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1C61KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1C61 Triton VS",
        "lcode1": "L5986",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1C61-KIT",
        "cost": "1270.06",
        "reimbursement": "7892",
        "percent": "16%",
        "pdac": "11/28/2012",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"PFDRPLFOOT",
        "manufacturer": "WillowWood",
        "name": "Pathfinder II",
        "lcode1": "L5986",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "PFDRPL-FOOT",
        "cost": "1369.52",
        "reimbursement": "7892",
        "percent": "17%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"R1401KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Silhouette VS",
        "lcode1": "L5986",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "R14-01-KIT",
        "cost": "968.47",
        "reimbursement": "7892",
        "percent": "12%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"R15KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Silhouette LP VS",
        "lcode1": "L5986",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "R15-KIT",
        "cost": "968.47",
        "reimbursement": "7892",
        "percent": "12%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1C51FOOTKIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Taleo VS 1C51",
        "lcode1": "L5986",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1C51-FOOT-KIT",
        "cost": "1537",
        "reimbursement": "7892",
        "percent": "19%",
        "pdac": "11/21/2020",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"RUSHRAMPAGETWO",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "RUSH_Rampage",
        "lcode1": "L5986",
        "lcode2": "L5987",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "RUSH RAMPAGE",
        "cost": "1676.34",
        "reimbursement": "7892",
        "percent": "21%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },


]


const  VertShock = [

    {
        "valAssign":"RS1KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Renegade",
        "lcode1": "L5987",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "RS1-KIT",
        "cost": "937.52",
        "reimbursement": "7260.04",
        "percent": "13%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"RS6KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Low Profile Renegade",
        "lcode1": "L5987",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "RS6-KIT",
        "cost": "937.52",
        "reimbursement": "7260.04",
        "percent": "13%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"M005FOOTKIT",
        "manufacturer": "WillowWood",
        "name": "Meta Shock",
        "lcode1": "L5987",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "M005-FOOT-KIT",
        "cost": "1353.62",
        "reimbursement": "7260.04",
        "percent": "19%",
        "pdac": "3/24/2021",
        "image": "../images/",
"link":""
      },


]

const  FlexWalkMultiAxialAnkleVac = [

    {
        "valAssign":"1C62KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1C62 Triton w/ Harmony System",
        "lcode1": "L5987",
        "lcode2": "L5986",
        "lcode3": "L5781",
        "lcode4": "",
        "hdcode": "1C62-KIT",
        "cost": " 3,000.69 ",
        "reimbursement": "11930",
        "percent": "25%",
        "pdac": "11/1/2020",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1C52KIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Taleo Harmony 1C52",
        "lcode1": "L5987",
        "lcode2": "L5986",
        "lcode3": "L5781",
        "lcode4": "",
        "hdcode": "1C52-KIT",
        "cost": " 3,387.08 ",
        "reimbursement": "11930",
        "percent": "28%",
        "pdac": "11/21/2020",
        "image": "../images/",
"link":""
      },

]


const  L5999 = [

    {
        "valAssign":"STOMPERFOOT",
        "manufacturer": "Stomper",
        "name": "Stomper Prosthetic Foot",
        "lcode1": "L5999",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "STOMPER-FOOT",
        "cost": "67.58",
        "reimbursement": "#N/A",
        "percent": "#N/A",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"FSX008FOOT",
        "manufacturer": "Ossur",
        "name": "Flex-Run with Nike Sole",
        "lcode1": "L5999",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "FSX008-FOOT",
        "cost": "1290.83",
        "reimbursement": "#N/A",
        "percent": "#N/A",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"175130FOOT",
        "manufacturer": "Fillauer",
        "name": "Obsidian Running Blade (Adult or Pediatric)",
        "lcode1": "L5999",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "175-130-FOOT",
        "cost": "1450.88",
        "reimbursement": "#N/A",
        "percent": "#N/A",
        "pdac": "11/18/2020",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"FSX00FOOT",
        "manufacturer": "Ossur",
        "name": "Cheetah",
        "lcode1": "L5999",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "FSX00-FOOT",
        "cost": "1486.33",
        "reimbursement": "#N/A",
        "percent": "#N/A",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/cheetah_foot_adult.jpg"
      },
      {
        "valAssign":"1E90",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Sprinter",
        "lcode1": "L5999",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1E90",
        "cost": "1574.69",
        "reimbursement": "#N/A",
        "percent": "#N/A",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"VF85FOOT",
        "manufacturer": "Biodapt",
        "name": "Versa Foot",
        "lcode1": "L5999",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "VF85-FOOT",
        "cost": "3386.7",
        "reimbursement": "#N/A",
        "percent": "#N/A",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"VF85FOOTTWO",
        "manufacturer": "Biodapt",
        "name": "Versa2",
        "lcode1": "L5999",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "VF85-FOOT",
        "cost": "3386.7",
        "reimbursement": "#N/A",
        "percent": "#N/A",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"PFP0FOOT",
        "manufacturer": "Ossur",
        "name": "Pro-flex Pivot",
        "lcode1": "L5999",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "PFP0-FOOT",
        "cost": "6738.42",
        "reimbursement": "#N/A",
        "percent": "#N/A",
        "pdac": "9/1/2018",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"PENDTWO",
        "manufacturer": "Biodapt",
        "name": "Versa2 HD",
        "lcode1": "L5999",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "PENDING",
        "cost": "Pending",
        "reimbursement": "#N/A",
        "percent": "#VALUE!",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"PENDTHREE",
        "manufacturer": "Biodapt",
        "name": "Versa Alpine",
        "lcode1": "L5999",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "PENDING",
        "cost": "Pending",
        "reimbursement": "#N/A",
        "percent": "#VALUE!",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },


]


const  MiscFeet = [

    {
        "valAssign":"SKFOOT",
        "manufacturer": "College_Park",
        "name": "Sidekicks  feetArray for Stubbies",
        "lcode1": "L5210",
        "lcode2": "L5920",
        "lcode3": "L5972",
        "lcode4": "L5986",
        "hdcode": "SK-FOOT",
        "cost": "444.46",
        "reimbursement": "3962",
        "percent": "11%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"ACCFOOT",
        "manufacturer": "College_Park",
        "name": "Accent (without dynamic pylon)",
        "lcode1": "L5981",
        "lcode2": "L5985",
        "lcode3": "L5986",
        "lcode4": "L5990",
        "hdcode": "ACC-FOOT",
        "cost": "722.76",
        "reimbursement": "5738",
        "percent": "13%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"ACCFOOTTWO",
        "manufacturer": "College_Park",
        "name": "Accent (with dynamic pylon)",
        "lcode1": "L5981",
        "lcode2": "L5986",
        "lcode3": "L5990",
        "lcode4": "",
        "hdcode": "ACC-FOOT",
        "cost": "722.76",
        "reimbursement": "5453",
        "percent": "13%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"XMP27A",
        "manufacturer": "KISS",
        "name": " feetArray for Stubbies",
        "lcode1": "L5920",
        "lcode2": "L5972",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "CMP27/A",
        "cost": "272.69",
        "reimbursement": "908",
        "percent": "30%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"EVACFOOT",
        "manufacturer": "Blatchford",
        "name": "Echelon Vacuum",
        "lcode1": "L5781",
        "lcode2": "L5968",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "EVAC-FOOT",
        "cost": "3290.96",
        "reimbursement": "10695",
        "percent": "31%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"RUNFOOTKIT",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Runway",
        "lcode1": "L5981",
        "lcode2": "L5990",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "RUN-FOOT-KIT",
        "cost": "1498.08",
        "reimbursement": "4820",
        "percent": "31%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"PLA0FOOT",
        "manufacturer": "Ossur",
        "name": "Pro-flex LP Align",
        "lcode1": "L5981",
        "lcode2": "L5986",
        "lcode3": "L5990",
        "lcode4": "",
        "hdcode": "PLA0-FOOT",
        "cost": "1750.06",
        "reimbursement": "5453",
        "percent": "32%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1C20",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "Prosymes",
        "lcode1": "L5910",
        "lcode2": "L5981",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1C20",
        "cost": "1465.29",
        "reimbursement": "3351",
        "percent": "44%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"HSFOOT",
        "manufacturer": "Dycor",
        "name": "H2U",
        "lcode1": "L5972",
        "lcode2": "L5984",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "HS-FOOT",
        "cost": "370.15",
        "reimbursement": "947",
        "percent": "39%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1AFOOT",
        "manufacturer": "Dycor",
        "name": "ATM (Single Axis)",
        "lcode1": "L5975",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1A-FOOT",
        "cost": "254.83",
        "reimbursement": "468",
        "percent": "54%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1A29",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1A29 Greissinger (Coding option 2)",
        "lcode1": "L5975",
        "lcode2": "L5999",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1A29",
        "cost": "260.44",
        "reimbursement": "468",
        "percent": "56%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1A29TWO",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1A29 Greissinger (Coding option 1)",
        "lcode1": "L5972",
        "lcode2": "L5999",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1A29",
        "cost": "260.44",
        "reimbursement": "379",
        "percent": "69%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1A29THREE",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "1A29 Greissinger (Coding option 3)",
        "lcode1": "L5978",
        "lcode2": "L5999",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1A29",
        "cost": "260.44",
        "reimbursement": "291",
        "percent": "89%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"FDS",
        "manufacturer": "Dycor",
        "name": "Symes",
        "lcode1": "L5975",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "FDS",
        "cost": "519.93",
        "reimbursement": "468",
        "percent": "111%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"EVAQ8",
        "manufacturer": "Proteor_Ability_Freedom",
        "name": "Evaq8_line_addition_for_Rampage_HiPro_Rogue",
        "lcode1": "L5781",
        "lcode2": "",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "EVAQ8 - Must select which model",
        "cost": "0",
        "reimbursement": "4038",
        "percent": "0%",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"PENDFOUR",
        "manufacturer": "College_Park",
        "name": "Orbit",
        "lcode1": "L5981",
        "lcode2": "L5984",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "PENDING",
        "cost": "Pending",
        "reimbursement": "3558",
        "percent": "#VALUE!",
        "pdac": "5/21/2021",
        "image": "../images/",
"link":""
      },
      {
        "valAssign":"1A11",
        "manufacturer": "Otto_Bock_Freedom",
        "name": "emPower MPF",
        "lcode1": "L5973",
        "lcode2": "L5969",
        "lcode3": "",
        "lcode4": "",
        "hdcode": "1A1-1",
        "cost": "27000",
        "reimbursement": "N/A**",
        "percent": "#VALUE!",
        "pdac": "NO pdac APPROVAL",
        "image": "../images/",
"link":""
      },


]




   export { K2FlexKeelMultiAxialRot, FlexFootMultiAxialAnkle, FlexWalk, FlexWalkMultiAxial, VertShockAxialRot, VertShockMultiAxialRot, VertShock, MiscFeet, L5999, FlexWalkMultiAxialAnkleVac, k2FlexKeelhydraMulti, FlexFoot, MultiAxialDynamResp, EnergyStore, SingAxis, Microprocessor, k3FlexHydrauMulti, K3FlexHydrauMultiVertShock, SACH, K2FlexHeel, K2FlexKeelAxialRotVert};




