const lockLiners = 
[
{"image": "../images/liners/ABL_ABK_LINER.jpg", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Basic Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"ABL"},
{"image": "../images/liners/", "manufacturer":"SILIPOS HOLDING LLC","name":"Low Activity Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"LOWLINER"},
{"image": "../images/liners/", "manufacturer":"THERMO-PLY, INC.","name":"Encore Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"ENCLINER"},
{"image": "../images/liners/dg-liner.jpg", "manufacturer":"SILIPOS HOLDING LLC","name":"Dura Gel Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"DGLINER"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Clearpro Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SSALINER"},
{"image": "../images/liners/alps_apdt_main_new.jpg", "manufacturer":"ALPS SOUTH LLC","name":"Anterior Posterior Locking Liner","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"APDTLINER"},
{"image": "../images/liners/akl-liner.jpg", "manufacturer":"ALPS SOUTH LLC","name":"Extreme Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"AKLINER"},
{"image": "../images/liners/akhd_liner.jpg", "manufacturer":"ALPS SOUTH LLC","name":"Extreme Locking (HD Gel)","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"AKHDLINER"},
{"image": "../images/liners/gp-liner.jpg", "manufacturer":"ALPS SOUTH LLC","name":"General Purpose Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"GPLINER"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Superior Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SUPLINER"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Superior Locking (HD Gel)","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SIPLINER1"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"WintersGel Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"WGLINER"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Uniform Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"T010LINER"},
{"image": "../images/liners/alps_ecdthd_new_main.jpg", "manufacturer":"ALPS SOUTH LLC","name":"Eco Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"ECDTHDLINER"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Extreme Liner (with valve)","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"VKDTLINER"},
{"image": "../images/liners/ALL-Liner.jpg", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Original Alpha MP 6mm Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"ALLLINER"},
{"image": "../images/liners/a442_liner_image.jpg", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"AK Symetrical Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"A442LINER"},
{"image": "../images/liners/expressliner.jpg", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Express Locking AK","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"ExpressAKLiner"},
{"image": "../images/liners/expressliner.jpg", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Express Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"EXPRESSLINER"},
{"image": "../images/liners/ALL-Liner.jpg", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Max Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"ALLLINER1"},
{"image": "../images/liners/ALL-Liner.jpg", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Original Alpha Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"ALLLINER3"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Alpha Silicone Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"S35LINER"},
{"image": "../images/liners/a351_liner_image_1_.jpg", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Alpha Select Classic 6mm Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"A351LINER"},
{"image": "../images/liners/a352_liner_image_1_.jpg", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Alpha Select Classic Progressive Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"A352LINER"},
{"image": "../images/liners/ALL-Liner.jpg", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Spirit Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"ALLLINER4"},
{"image": "../images/liners/h442-liner.jpg", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"AK Hybrid Locking ","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"AKLLINER"},
{"image": "../images/liners/akl-liner.jpg", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"AK Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"AKLLINER1"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"AK Silicone Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"S44LINER"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Alpha Select Hybrid Gel Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"H351LINER1"},
{"image": "../images/liners/", "manufacturer":"THERMO-PLY, INC.","name":"Encore II Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"ENCIILINER"},
{"image": "../images/liners/", "manufacturer":"THERMO-PLY, INC.","name":"Encore V Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"ENCVLINER"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"SoFlex Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SBKLINER"},
{"image": "../images/liners/alps_ezf_new_main.jpg", "manufacturer":"ALPS SOUTH LLC","name":"EZ Flex Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"EZFLINER"},
{"image": "../images/liners/", "manufacturer":"COLLEGE PARK INDUSTRIES, INC.","name":"Genesee Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"GLKLINER"},
{"image": "../images/liners/", "manufacturer":"COLLEGE PARK INDUSTRIES, INC.","name":"Genesee Locking 2pk","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"GLKLINER2"},
{"image": "../images/liners/alps_lsk_liner_new_main.jpg", "manufacturer":"ALPS SOUTH LLC","name":"PRO Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"LSXLINER"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Liberty Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"VSLINER"},
{"image": "../images/liners/EL-LINER.jpg", "manufacturer":"ALPS SOUTH LLC","name":"Easy Liner Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"ELLINER"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Thermo Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"TFLINER"},
{"image": "../images/liners/6y90_liner_image.jpg", "manufacturer":"OTTO BOCK","name":"Copolymer Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SIXY90"},
{"image": "../images/liners/30-LOCKING-LINER.jpg", "manufacturer":"ST&G USA CORP","name":"ADAPT Locking TT","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"THIRTYLOCKING"},
{"image": "../images/liners/30-LOCKING-LINER.jpg", "manufacturer":"ST&G USA CORP","name":"ADAPT Locking TF","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"THIRTYLOCKING1"},
{"image": "../images/liners/3020-LINER.jpg", "manufacturer":"ST&G USA CORP","name":"Parasil Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"THIRTY20LINER"},
{"image": "../images/liners/BDL-LINER.jpg", "manufacturer":"BULLDOG TOOLS, INC.","name":"Imagine Locking 20 cm","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"BDLLINER"},
{"image": "../images/liners/BDL-LINER.jpg", "manufacturer":"BULLDOG TOOLS, INC.","name":"Imagine Locking 24 & 28 cm","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"BDLLINER1"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"AK Smart Seal Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SADTLINER"},
{"image": "../images/liners/3030INF-LINER.jpg", "manufacturer":"ST&G USA CORP","name":"Hydro Mag Locking Coated Hydro Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"THIRTY30INFLINER"},
{"image": "../images/liners/3040INF-LINER.jpg", "manufacturer":"ST&G USA CORP","name":"Hydro Mag Locking Fabric Premier Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"THIRTY40INFLINER"},
{"image": "../images/liners/3040INF-LINER.jpg", "manufacturer":"ST&G USA CORP","name":"BK/TT Mag Fabric Premier Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"THIRTY4025"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"SmartTemp Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"T35"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"AK SmartTemp Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"T4401"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Alpha SmartTemp AK Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"P44012"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Alpha SmartTemp Locking Gel","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"P35189"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"Aegis TF Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"TFLINER123"},
{"image": "../images/liners/", "manufacturer":"ST&G USA CORP","name":"Parasil TF AK Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"3070LINER1"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"Streamline Uncovered Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"STREAMLINE1"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"Aegis Streamline no Cover Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"STREAMLINE2"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"Aegis Streamline w/ Cover Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"STREAMLINE3"},
{"image": "../images/liners/", "manufacturer":"ST&G USA CORP","name":"Hydro Mag AK Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"THIRTY50LINER"},
{"image": "../images/liners/", "manufacturer":"ST&G USA CORP","name":"AK/TF Mag Liner Premier Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"THIRTY60LINER"},
{"image": "../images/liners/iceross_original.jpg", "manufacturer":"OSSUR AMERICAS, INC","name":"Original Locking no Cover","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"ICEROSSORIGINALLINER"},
{"image": "../images/liners/iceross_original.jpg", "manufacturer":"OSSUR AMERICAS, INC","name":"Original Locking w/ Cover","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"ICEROSSORIGINALLINER2"},
{"image": "../images/liners/", "manufacturer":"BROADBAY LLC","name":"Broadbay Comfort Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"FOURTYLLINER"},
{"image": "../images/liners/", "manufacturer":"BLATCHFORD, INC","name":"Blatchford Comfort Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"CTTCP"},
{"image": "../images/liners/", "manufacturer":"BROADBAY LLC","name":"Classic Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"FIFTYLLINER"},
{"image": "../images/liners/", "manufacturer":"BROADBAY LLC","name":"Classic Soft Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"FIFTYONELLINER"},
{"image": "../images/liners/", "manufacturer":"BROADBAY LLC","name":"Comfort Soft Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"FOURTYONELLINER"},
{"image": "../images/liners/", "manufacturer":"DAW INDUSTRIES INC","name":"CoolLiner Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"DCLPLINER"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"SKEO Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SIXY42"},
{"image": "../images/liners/6y42_image.jpg", "manufacturer":"OTTO BOCK","name":"SKEO Pure","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SIXY43"},
{"image": "../images/liners/6y43_liner_image.jpg", "manufacturer":"OSSUR AMERICAS, INC","name":"Ossur Comfort Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"COMFORTLINER"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Comfort Wave Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"COMFORTLINER2"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"Balance Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SIXY93"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Sensitive Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":" M8914"},
{"image": "../images/liners/", "manufacturer":"DAW INDUSTRIES INC","name":"CoolLiner Tri-Gel Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"DCPFLINER"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"Aegis Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"BKULINER"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"BK Seal-Pro Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SPLINER"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"Ultimate Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"BKULINER2"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"TF Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"I703LINER"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"AK Seal-Pro Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SPTF1"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Protect 3C Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"MC971LINER"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Relax 3C Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"M89941"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Relax 6C Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"M89942"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Synergy Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"ICEROSSSYNERGY1"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Synergy Wave Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"ICEROSSSYNERGY2"},
{"image": "../images/liners/6y523_Image-1.jpg", "manufacturer":"OTTO BOCK","name":"Simplicity PUR Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SIXY523"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Relax TFC Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"M8958"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Relax TFS Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"M8957"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Dermo Uni Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"I4X0LINER"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Dermo Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"IICEROSSLINER"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Dermo Wave Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"IICEROSSLINER23"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"SKEO TT 3D Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SIXY78LINER"},
{"image": "../images/liners/6y75_liner_image.jpg", "manufacturer":"OTTO BOCK","name":"SKEO w/ Skinguard Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SIXY78LINER"},
{"image": "../images/liners/", "manufacturer":"BROADBAY LLC","name":"AK Control Locking 38mm","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SIXTYL1LINER"},
{"image": "../images/liners/", "manufacturer":"BROADBAY LLC","name":"AK Control Locking 20mm","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SIXTYL5LINER"},
{"image": "../images/liners/", "manufacturer":"DAW INDUSTRIES INC","name":"CoolLiner VSC Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"DCLPSCLINER"},
{"image": "../images/liners/", "manufacturer":"PROSTHETIC DESIGN, INC.","name":"SealMate Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SM44"},
{"image": "../images/liners/", "manufacturer":"BLATCHFORD, INC","name":"Breathe Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"SBBTTLP"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"AKOS TFC Conical Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"M89561234"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"AKOS TF Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q1"},
{"image": "../images/liners/", "manufacturer":"BAUERFEIND USA, INC.","name":"SoftSkin S50 Air Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q2"},
{"image": "../images/liners/", "manufacturer":"BAUERFEIND USA, INC.","name":"SoftSkin S50 Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q134"},
{"image": "../images/liners/", "manufacturer":"BAUERFEIND USA, INC.","name":"SoftSkin w/ Cover Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q3"},
{"image": "../images/liners/6y85_liner_image.jpg", "manufacturer":"OTTO BOCK","name":"SKEO AK w/ Skinguard Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q4"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"SKEO TK Locking w/ Antibac","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q5"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"SKEO Unique BK Std Repl Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q6"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Sport Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q7"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Sport Locking 2pk","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q8"},
{"image": "../images/liners/", "manufacturer":"BAUERFEIND USA, INC.","name":"SoftSkin Air Sport Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q9"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"SKEO Unique BK Shp Repl Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q11"},
{"image": "../images/liners/", "manufacturer":"BAUERFEIND USA, INC.","name":"Softskin TF Air Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q12"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"SKEO Unique AK Std Repl Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q13"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"SKEO Unique BK Std Alt Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q14"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"SKEO Unique BK Shp Alt Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q15"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"SKEO Unique BK Std New Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q16"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"SKEO Unique BK Shp New Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q17"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"SKEO Unique AK Std Alt Locking","lcode":"L5673" ,"reimbursement":"$709.62 ", "valAssign":"Q18"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"SKEO Unique AK Std New Locking","lcode":"L5673" ,"reimbursement":"$709.62 ","percent":"89%"}
]

const cushLiner = 
[{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Cleargen Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q19"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Basic Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q20"},
{"image": "../images/liners/", "manufacturer":"SILIPOS HOLDING LLC","name":"Low Activity Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q21"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Super Stretch Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q22"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Uniform Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q23"},
{"image": "../images/liners/enc_liner_image.jpg", "manufacturer":"THERMO-PLY, INC.","name":"Encore Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q24"},
{"image": "../images/liners/", "manufacturer":"SILIPOS HOLDING LLC","name":"Dura Gel Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q25"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"Streamline Cushion no cover","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q26"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"Streamline Cushion w/ cover","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q27"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Anterior Posterior Cushion Liner","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q28"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Extreme Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q29"},
{"image": "../images/liners/akhd_liner.jpg", "manufacturer":"ALPS SOUTH LLC","name":"Extreme Cushion (HD Gel)","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q30"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Full Suction Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q31"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"General Purpose Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q32"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Proximal Seal Interface Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q33"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Superior Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q34"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"WintersGel Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q35"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"WintersGel Suction Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q36"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Original Alpha MP Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q37"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"AK Silicone Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q38"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"AK Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q39"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"AK Hybrid Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q40"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Alpha Original Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q41"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Alpha Silicone Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q42"},
{"image": "../images/liners/expressliner.jpg", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Express Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q43"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Max Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q44"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Select Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q45"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Spirit Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q45"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Eco Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q46"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Guardian (HD Gel) Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q47"},
{"image": "../images/liners/ENC-II-LINER.jpg", "manufacturer":"THERMO-PLY, INC.","name":"Encore II Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q48"},
{"image": "../images/liners/ENC-V-LINER.jpg.jpg", "manufacturer":"THERMO-PLY, INC.","name":"Encore V Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q49"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"SoFlex Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q50"},
{"image": "../images/liners/genesee-liner_3.png", "manufacturer":"COLLEGE PARK INDUSTRIES, INC.","name":"Genesee Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q51"},
{"image": "../images/liners/genesee-liner_3.png", "manufacturer":"COLLEGE PARK INDUSTRIES, INC.","name":"Genesee Cushion 2pk","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q52"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"PRO Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q53"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"AK SmartTemp Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q54"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"SmartTemp Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q55"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Easy Liner Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q56"},
{"image": "../images/liners/BDL-LINER.jpg", "manufacturer":"BULLDOG TOOLS, INC.","name":"Imagine Cushion 20cm Circ.","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q57"},
{"image": "../images/liners/BDL-LINER.jpg", "manufacturer":"BULLDOG TOOLS, INC.","name":"Imagine Cushion 24 & 28 Circ.","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q58"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"Copolymer Cushion (Basic Cushion)","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q59"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Duo Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q60"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"SmartTemp Cushion & Gel Sock","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q61"},
{"image": "../images/liners/3020-LINER.jpg", "manufacturer":"ST&G USA CORP CONSIGNMENT","name":"Parasil Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q62"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"AK Smart Seal Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q63"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Smart Seal Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q64"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"AK Seal-Pro Cushion (No fabric cover)","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q6"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"Seal-Pro Cushion (No fabric cover)","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q65"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"AK Seal-Pro Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q66"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"Seal-Pro Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q67"},
{"image": "../images/liners/", "manufacturer":"EVOLUTION INDUSTRIES","name":"Origin Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q68"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Alpha SmartTemp AK Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q69"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"Alpha SmartTemp Cushion Gel","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q70"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"Aegis TF Cushion ","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q71"},
{"image": "../images/liners/", "manufacturer":"DAW INDUSTRIES INC","name":"CoolLiner Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q72"},
{"image": "../images/liners/", "manufacturer":"BROADBAY LLC","name":"Contex Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q73"},
{"image": "../images/liners/", "manufacturer":"BROADBAY LLC","name":"Contex Soft Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q74"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"Aegis Ultimate Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q75"},
{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"Ultimate Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q76"},
{"image": "../images/liners/", "manufacturer":"EVOLUTION INDUSTRIES","name":"Origin XV Cushion Size 0","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q77"},
{"image": "../images/liners/", "manufacturer":"EVOLUTION INDUSTRIES","name":"Origin X Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q78"},
{"image": "../images/liners/", "manufacturer":"EVOLUTION INDUSTRIES","name":"Origin XV Cushion Size 1-8","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q79"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"Balance Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q80"},
{"image": "../images/liners/", "manufacturer":"BROADBAY LLC","name":"Classic Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q81"},
{"image": "../images/liners/", "manufacturer":"BROADBAY LLC","name":"Classic Soft Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q82"},
{"image": "../images/liners/", "manufacturer":"BROADBAY LLC","name":"Broadbay Comfort Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q83"},
{"image": "../images/liners/", "manufacturer":"BROADBAY LLC","name":"Comfort Soft Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q84"},
{"image": "../images/liners/", "manufacturer":"DAW INDUSTRIES INC","name":"CoolLiner Tri-Gel Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q85"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Ossur Comfort Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q86"},
{"image": "../images/liners/", "manufacturer":"BLATCHFORD, INC","name":"Blatchford Comfort Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q87"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"Simplicity PUR Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q88"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"SKEO Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q89"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"DVS Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q90"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Synergy Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q91"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Synergy Wave Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q92"},
{"image": "../images/liners/", "manufacturer":"DAW INDUSTRIES INC","name":"CoolLiner VSC Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q93"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Protect 3C Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q94"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Dermo Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q95"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Dermo Wave Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q96"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Relax 3C Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q97"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"ProSeal Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q98"},
{"image": "../images/liners/", "manufacturer":"BAUERFEIND USA, INC.","name":"SoftSkin w/ Cover Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q99"},
{"image": "../images/liners/", "manufacturer":"BAUERFEIND USA, INC.","name":"SoftSkin S50 Air Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q100"},
{"image": "../images/liners/", "manufacturer":"BAUERFEIND USA, INC.","name":"SoftSkin S50 Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q101"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"Simplicity PUR Cushion (Tapered)","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q102"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"3D PUR Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q103"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"3D PUR Cushion with skinguard","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q104"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"3D PUR Cushion with fabric","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q105"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"3D PUR Cushion with fabric and skinguard","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q106"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"AK Alpha TruSeal Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q107"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"PUR Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q108"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"PUR Cushion with cover","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q109"},
{"image": "../images/liners/", "manufacturer":"BLATCHFORD, INC","name":"Breathe Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q110"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Activa Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q111"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK","name":"Hybrid Cushion","lcode":"L5679" ,"reimbursement":"$591.32 ","percent":"72%"}]

const sealLiner = [{"image": "../images/liners/", "manufacturer":"EVOLUTION INDUSTRIES","name":"Echo Seal In No Hole","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q112"},
{"image": "../images/liners/", "manufacturer":"EVOLUTION INDUSTRIES","name":"Aura Seal In","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q113"},
{"image": "../images/liners/", "manufacturer":"EVOLUTION INDUSTRIES","name":"Echo Seal in w/ Hole","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q114"},
{"image": "../images/liners/", "manufacturer":"ALPS SOUTH LLC","name":"Guardian Seal In","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q115"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"X Seal In Classic","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q116"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"X Seal In Grip","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q117"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"X Seal In Volume","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q118"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK HEALTH CARE-DIRECT","name":"ProSeal Seal In","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q119"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"X Seal In","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q120"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"X Lock Seal In","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q121"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Dermo Seal In","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q122"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"X TF Seal In","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q123"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"4Seal Seal In Conical","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q124"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Medi 4Seal TFS Seal In","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q125"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"TT Seal In X5","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q126"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"X5 Seal In","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q127"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"V Seal In","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q128"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"TF Seal In","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q129"},
{"image": "../images/liners/", "manufacturer":"OTTO BOCK HEALTH CARE-STOCK","name":"SKEO Seal In","lcode":"L5679" ,"reimbursement":"$591.32 ", "valAssign":"Q130"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"TT Wave Seal In","lcode":"L5679" ,"reimbursement":"$591.32 ","percent":" "}]

const custLiner= [{"image": "../images/liners/", "manufacturer":"ENGINEERED SILICONE PRODUCTS","name":"ESP Custom","lcode":0 ,"reimbursement":"N/A", "valAssign":"Q131"},
{"image": "../images/liners/", "manufacturer":"EVOLUTION INDUSTRIES","name":"Evolution Custom","lcode":0 ,"reimbursement":"N/A", "valAssign":"Q132"},
{"image": "../images/liners/", "manufacturer":"OSSUR AMERICAS, INC","name":"Ossur Custom","lcode":0 ,"reimbursement":"N/A", "valAssign":"Q133"},
{"image": "../images/liners/", "manufacturer":"WILLOWWOOD GLOBAL, LLC","name":"WillowWood Custom","lcode":0 ,"reimbursement":"N/A","percent":" "}]

export {lockLiners, cushLiner, sealLiner, custLiner}; 