// const kneeArray 

const K14BFEA = [
{"category":"K1/K2 4Bar with Friction, Extension assist: L5611, L5850  base",
"manufacturer":"Fillauer_Knee",
"name":"Mighty Mite",
"lcode1":"L5611",
"lcode2":"L5850",
"lcode3":" ",
"lcode4":" ",
"lcode4": "" ,
"lcode5": "" ,
"lcode6": "" ,
"lcode6": "" ,
"hdcode":"FC100510",
"cost":434.83,
"reimbursement":1735.59,
"percent":"25%",
"BestValue":"STG 1312 S and T models",
"pdac":"No",
"valuePer":35,
"link":"",
"linkname":"",
"image":"../images/fc100510_image_1.jpg"},

{"category":"K1/K2 4Bar with Friction, Extension assist: L5611, L5850  base",
"manufacturer":"Ossur_Medi_Knee",
"name":"Balance Knee OM8",
"lcode1":"L5611",
"lcode2":"L5850",
"lcode3":" ",
"lcode4":" ",
"lcode4": "" ,
"lcode5": "" ,
"lcode6": "" ,
"lcode6": "" ,
"hdcode":"OM8HD",
"cost":465.08,
"reimbursement":1735.59,
"percent":"27%",
"BestValue":"STG 1312 S and T models",
"pdac":"No",
"valuePer":35,
"link":"",
"linkname":"",
"image":"../images/OM8HD.jpg"},

{"category":"K1/K2 4Bar with Friction, Extension assist: L5611, L5850  base",
"manufacturer":"Ti_Med_Knee",
"name":"PK-400",
"lcode1":"L5611",
"lcode2":"L5850",
"lcode3":" ",
"lcode4":" ",
"lcode4": "" ,
"lcode5": "" ,
"lcode6": "" ,
"lcode6": "" ,
"hdcode":"PK-400",
"cost":484.16,
"reimbursement":1735.59,
"percent":"28%",
"BestValue":"STG 1312 S and T models",
"pdac":"No",
"valuePer":35,
"link":"",
"linkname":"",
"image":"../images/pk_400_image.jpg"},

{"category":"K1/K2 4Bar with Friction, Extension assist: L5611, L5850  base",
"manufacturer":"STG_Knee",
"name":"P317",
"lcode1":"L5611",
"lcode2":"L5850",
"lcode3":"",
"lcode4":"",
"lcode4":null,
"lcode5":null,
"lcode6":null,
"lcode6":null,
"hdcode":"P317A-KNEE",
"cost":509.13,
"reimbursement":1735.59,
"percent":"29%",
"BestValue":"STG 1312 S and T models",
"pdac":"No",
"valuePer":35,
"link":"",
"linkname":"",
"image":"../images/P317.jpg"},

{"category":"K1/K2 4Bar with Friction, Extension assist: L5611, L5850  base",
"manufacturer":"Blatchford_Knee",
"name":"019245 (4-bar knee)",
"lcode1":"L5611",
"lcode2":"L5850",
"lcode3":"L5920",
"lcode4":"",
"lcode4":null,
"lcode5":null,
"lcode6":null,
"lcode6":null,
"hdcode":"019245",
"cost":1005.71,
"reimbursement":2265.11,
"percent":"44%",
"BestValue":"STG 1312 S and T models",
"pdac":"No",
"valuePer":10,
"link":"",
"linkname":"",
"image":"../images/019245_image.jpg"},

{"category":"K1/K2 4Bar with Friction, Extension assist: L5611, L5850  base",
"manufacturer":"Otto_Bock_Knee",
"name":"3R36 Modular Polycentric",
"lcode1":"L5611",
"lcode2":"L5850",
"lcode3":" ",
"lcode4":" ",
"lcode4": "" ,
"lcode5": "" ,
"lcode6": "" ,
"lcode6": "" ,
"hdcode":"3R36",
"cost":875.78,
"reimbursement":1735.59,
"percent":"50%",
"BestValue":"STG 1312 S and T models",
"pdac":"No",
"valuePer":10,
"link":"",
"linkname":"",
"image":"../images/3R36_Image.jpg"},

{"category":"K1/K2 4Bar with Friction, Extension assist: L5611, L5850  base",
"manufacturer":"Otto_Bock_Knee",
"name":"3R30 Modular Polycentric",
"lcode1":"L5611",
"lcode2":"L5850",
"lcode3":" ",
"lcode4":" ",
"lcode4": "" ,
"lcode5": "" ,
"lcode6": "" ,
"lcode6": "" ,
"hdcode":"3R30",
"cost":1009.19,
"reimbursement":1735.59,
"percent":"58%",
"BestValue":"STG 1312 S and T models",
"pdac":"No",
"valuePer":10,
"link":"",
"linkname":"",
"image":"../images/3R30-01-1200x1200.jpg"},

    ];

const kneeTwo = [
{"category":"K1/K2 4Bar with Friction, Extension assist &  Lock: L5611, L5850, L5925  base","manufacturer":"STG_Knee","name":"L1321AP","lcode1":"L5611","lcode2":"L5850","lcode3":"L5925","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"L1321AP","cost":317.28,"reimbursement":2182.69,"percent":"15%","BestValue":"STG L1321AP","pdac":"1/1/2017","valuePer":75,"link":"","linkname":"",

                                                                                  "image":"../images/L1321AP.jpg"},
{"category":"K1/K2 4Bar with Friction, Extension assist &  Lock: L5611, L5850, L5925  base","manufacturer":"Trulife_Knee","name":"SSK 610A","lcode1":"L5611","lcode2":"L5850","lcode3":"L5925","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"SSK610A","cost":444.56,"reimbursement":2182.69,"percent":"20%","BestValue":"STG L1321AP","pdac":"No","valuePer":75,"link":"","linkname":"",
                                                                                  "image":"../images/SSK610A_Image.jpg"},
{"category":"K1/K2 4Bar with Friction, Extension assist &  Lock: L5611, L5850, L5925  base","manufacturer":"Ossur_Medi_Knee","name":"Medi Knee Model OFM1 and OFM1HD","lcode1":"L5611","lcode2":"L5850","lcode3":"L5925","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"OFM1HD","cost":569.8,"reimbursement":2182.69,"percent":"26%","BestValue":"STG L1321AP","pdac":"No","valuePer":35,"link":"","linkname":"",   
                                                                                  "image":"../images/OFM1HDSF_image.jpg"},
{"category":"K1/K2 4Bar with Friction, Extension assist &  Lock: L5611, L5850, L5925  base","manufacturer":"Trulife_Knee","name":"SSK602L Seattle Natural","lcode1":"L5611","lcode2":"L5850","lcode3":"L5925","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"SSK602L","cost":571.76,"reimbursement":2182.69,"percent":"26%","BestValue":"STG L1321AP","pdac":"No","valuePer":35,"link":"","linkname":"",
                                                                                  "image":"../images/trulife_image_ssk602l_main.jpg"},
{"category":"K1/K2 4Bar with Friction, Extension assist &  Lock: L5611, L5850, L5925  base","manufacturer":"Legworks_Knee","name":"All Terrain Knee ATK-PA-01","lcode1":"L5611","lcode2":"L5850","lcode3":"L5925","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"ATK-PA-01","cost":684.76,"reimbursement":2182.69,"percent":"31%","BestValue":"STG L1321AP","pdac":"No","valuePer":35,"link":"","linkname":"",
                                                                                  "image":"../images/ATK-PA-01.jpg"},
{"category":"K1/K2 4Bar with Friction, Extension assist &  Lock: L5611, L5850, L5925  base","manufacturer":"Proteor_Freedom_Knee","name":"1M102","lcode1":"L5611","lcode2":"L5850","lcode3":"L5925","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"TF1-G","cost":839.8,"reimbursement":2182.69,"percent":"38%","BestValue":"STG L1321AP","pdac":"No","valuePer":10,"link":"","linkname":"",
                                                                                  "image":"../images/1M102 Series.jpg"},
{"category":"K1/K2 4Bar with Friction, Extension assist &  Lock: L5611, L5850, L5925  base","manufacturer":"Otto_Bock_Knee","name":"3R32","lcode1":"L5611","lcode2":"L5850","lcode3":"L5925","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R32","cost":1043.62,"reimbursement":2182.69,"percent":"48%","BestValue":"STG L1321AP","pdac":"No","valuePer":10,"link":"","linkname":"",
                                                                                  "image":"../images/3R32_Image.jpg"},
{"category":"K1/K2 4Bar with Friction, Extension assist &  Lock: L5611, L5850, L5925  base","manufacturer":"Ti_Med_Knee","name":"KN-500 Knee (same as Kingsley AK-500 Polycentric Knee)","lcode1":"L5611","lcode2":"L5850","lcode3":"L5925","lcode4":"L5999","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"KN-500","cost":1745.01,"reimbursement":2182.69,"percent":"80%","BestValue":"STG L1321AP","pdac":"No","valuePer":10,"link":"","linkname":"",
                                                                                  "image":"../images/kn_500_knee_image.jpg"},
    ];

//     const kneeThree = [
// {"category":"K1/K2 4Bar with friction, Extension assist & Stance Flexion: L5611, L5850, L5845 base","manufacturer":"STG_Knee","name":"1324 AP","lcode1":"L5611","lcode2":"L5850","lcode3":"L5845","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"1324 AP","cost":663.62,"reimbursement":3544.51,"percent":"19%","BestValue":"STG 1324 AP","pdac":"8/1/2018","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/1324_AP.jpg"},
// {"category":"K1/K2 4Bar with friction, Extension assist & Stance Flexion: L5611, L5850, L5845 base","manufacturer":"Trulife_Knee","name":"SSK 617 Natural Stance Flexion","lcode1":"L5611","lcode2":"L5850","lcode3":"L5845","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"SSK617","cost":953.36,"reimbursement":3544.51,"percent":"27%","BestValue":"STG 1324 AP","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/trulife_image_ssk617_main.jpg"},
// {"category":"K1/K2 4Bar with friction, Extension assist & Stance Flexion: L5611, L5850, L5845 base","manufacturer":"Ossur_Medi_Knee","name":"Total Knee Unit Model 1100 Junior","lcode1":"L5611","lcode2":"L5850","lcode3":"L5845","lcode4":"","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"1100OSS","cost":1072.72,"reimbursement":3544.51,"percent":"30%","BestValue":"STG 1324 AP","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/1100oss_image.jpg"},
// {"category":"K1/K2 4Bar with friction, Extension assist & Stance Flexion: L5611, L5850, L5845 base","manufacturer":"Ossur_Medi_Knee","name":"Total Knee Unit Model 1900 (Friction)","lcode1":"L5611","lcode2":"L5850","lcode3":"L5845","lcode4":"","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"1900OSS","cost":1141.41,"reimbursement":3544.51,"percent":"32%","BestValue":"STG 1324 AP","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/1900oss_image.jpg"},
//     ];
//          const K14BarFESL = [                                                                                                                       
// {"category":"K1/K2 4Bar with Friction, Extension Assist, Stance Flexion & Lock: L5611, L5850, L5845, L5925 base","manufacturer":"STG_Knee","name":"L1324 AP","lcode1":"L5611","lcode2":"L5850","lcode3":"L5845","lcode4":"L5925","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"L1324 AP","cost":519.72,"reimbursement":3991.61,"percent":"13%","BestValue":"STG L1324 AP","pdac":"11/10/2016","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/1324_AP.jpg"},
// {"category":"K1/K2 4Bar with Friction, Extension Assist, Stance Flexion & Lock: L5611, L5850, L5845, L5925 base","manufacturer":"Ossur_Medi_Knee","name":"Medi Knee Model OFM1SF and OFM1SFHD","lcode1":"L5611","lcode2":"L5850","lcode3":"L5845","lcode4":"L5925","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"OFM1SFHD","cost":892.26,"reimbursement":3991.61,"percent":"22%","BestValue":"STG L1324 AP","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/OFM1HDSF_image.jpg"},
// {"category":"K1/K2 4Bar with Friction, Extension Assist, Stance Flexion & Lock: L5611, L5850, L5845, L5925 base","manufacturer":"Legworks_Knee","name":"All Terrain Knee w/ Stance Flexion ATK-SF-01","lcode1":"L5611","lcode2":"L5850","lcode3":"L5845","lcode4":"L5925","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"ATK-SF-01","cost":995.34,"reimbursement":3991.61,"percent":"25%","BestValue":"STG L1324 AP","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/legworks_image_atk-SF-01_main.jpg"},
// {"category":"K1/K2 4Bar with Friction, Extension Assist, Stance Flexion & Lock: L5611, L5850, L5845, L5925 base","manufacturer":"Otto_Bock_Knee","name":"3R62 Pheon","lcode1":"L5611","lcode2":"L5850","lcode3":"L5845","lcode4":"L5925","lcode4":null,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R62","cost":1039.32,"reimbursement":3991.61,"percent":"26%","BestValue":"STG L1324 AP","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/3r62_image.jpg"},
//     ];

//     const kneeSixteen = [
// {"category":"Single Axis  with Manual Lock: L5811  base" ,"manufacturer":"Blatchford_Knee","name":"Semi-Automatic Knee Lock (SAKL/Compact SAKL)","lcode1":"L5811","lcode2":" ","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"P239143","cost":276.11,"reimbursement":727.84,"percent":"38%","BestValue":"Blatchford Semi-Automatic Knee Lock","pdac":"No","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/P239143_Image.jpg"},
// {"category":"Single Axis  with Manual Lock: L5811  base" ,"manufacturer":"Blatchford_Knee","name":"P019267 (SAKL)","lcode1":"L5811","lcode2":"L5920","lcode3":"","lcode4":"","lcode4":null,"lcode5":null,"lcode6":null,"lcode6":null,"hdcode":"P019267","cost":304.6,"reimbursement":1257.36,"percent":"24%","BestValue":"Blatchford Semi-Automatic Knee Lock","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/P019267_Image.jpg"},
// {"category":"Single Axis  with Manual Lock: L5811  base" ,"manufacturer":"Otto_Bock_Knee","name":"3R40","lcode1":"L5811","lcode2":" ","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R40","cost":290.81,"reimbursement":727.84,"percent":"40%","BestValue":"Blatchford Semi-Automatic Knee Lock","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                  "image":"../images/3R40_Image.jpg"},
// {"category":"Single Axis  with Manual Lock: L5811  base" ,"manufacturer":"Otto_Bock_Knee","name":"3R41 Locking","lcode1":"L5811","lcode2":" ","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R41","cost":376.42,"reimbursement":727.84,"percent":"52%","BestValue":"Blatchford Semi-Automatic Knee Lock","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                  "image":"../images/3r41_image.jpg"},
// {"category":"Single Axis  with Manual Lock: L5811  base" ,"manufacturer":"Otto_Bock_Knee","name":"3R33 Titan","lcode1":"L5811","lcode2":"L5850","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R33","cost":575.2,"reimbursement":855.51,"percent":"67%","BestValue":"Blatchford Semi-Automatic Knee Lock","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                  "image":"../images/3R33_Image.jpg"},
// {"category":"Single Axis  with Manual Lock: L5811  base" ,"manufacturer":"Otto_Bock_Knee","name":"3R39 Knee Joint Children, locking","lcode1":"L5811","lcode2":" ","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R39","cost":706.87,"reimbursement":727.84,"percent":"97%","BestValue":"Blatchford Semi-Automatic Knee Lock","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                  "image":"../images/3r39_image.jpg"},
//     ];
//     const kneeFour = [
// {"category":"Safety knee with Extension Assist: L5812  base" ,"manufacturer":"STG_Knee","name":"1311S","lcode1":"L5812","lcode2":"L5850","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"1311S","cost":242.39,"reimbursement":691.83,"percent":"35%","BestValue":"STG 1311S","pdac":"No","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/1311.jpg"},
// {"category":"Safety knee with Extension Assist: L5812  base" ,"manufacturer":"Fillauer_Knee","name":"S.A.F.K.","lcode1":"L5812","lcode2":"L5850","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"SAFK-KNEE","cost":343.28,"reimbursement":691.83,"percent":"50%","BestValue":"STG 1311S","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/60821_image.jpg"},
// {"category":"Safety knee with Extension Assist: L5812  base" ,"manufacturer":"Otto_Bock_Knee","name":"3R15","lcode1":"L5812","lcode2":" ","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R15","cost":311.67,"reimbursement":564.16,"percent":"55%","BestValue":"STG 1311S","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                              "image":"../images/3R15_Image.jpg"},
// {"category":"Safety knee with Extension Assist: L5812  base" ,"manufacturer":"Fillauer_Knee","name":"W.A.L.K.","lcode1":"L5812","lcode2":"L5850","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"607-KNEE","cost":400.75,"reimbursement":691.83,"percent":"58%","BestValue":"STG 1311S","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                              "image":"../images/walk-knee-1-1.jpg"},
// {"category":"Safety knee with Extension Assist: L5812  base" ,"manufacturer":"Otto_Bock_Knee","name":"3R49","lcode1":"L5812","lcode2":"L5850","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R49","cost":675.75,"reimbursement":691.83,"percent":"98%","BestValue":"STG 1311S","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                              "image":"../images/3R49_Image.jpg"},
//     ];

//     const kneeFive = [
// {"category":"Safety Knee with Stance Flexion and Extension Assist: L5812, L5845, L5850 base","manufacturer":"Ossur_Medi_Knee","name":"Medi Knee Model OFM2 and OFM2HD","lcode1":"L5812","lcode2":"L5845","lcode3":"L5850","lcode4":"L5925","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"OFM2HD","cost":541.59,"reimbursement":2947.85,"percent":"18%","BestValue":"Ossur/Medi OFM2 & OMF2HD","pdac":"No","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/OFM2HD_image2new.jpg"},
// {"category":"Safety Knee with Stance Flexion and Extension Assist: L5812, L5845, L5850 base","manufacturer":"College_Park_Knee","name":"Guardian","lcode1":"L5812","lcode2":"L5845","lcode3":"L5850","lcode4":"L5925","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"GFKA 120","cost":516.75,"reimbursement":2947.85,"percent":"18%","BestValue":"Ossur/Medi OFM2 & OMF2HD","pdac":"No","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/gfka_120_image_main.jpg"},
// {"category":"Safety Knee with Stance Flexion and Extension Assist: L5812, L5845, L5850 base","manufacturer":"Cypress_Knee","name":"Adaptive Paseo ML","lcode1":"L5812","lcode2":"L5845","lcode3":"L5850","lcode4":"L5925","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"CA602-ML","cost":473.82,"reimbursement":2947.85,"percent":"16%","BestValue":"Ossur/Medi OFM2 & OMF2HD","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/adaptive_cypress_image_ca602_ml_main.jpg"},
// {"category":"Safety Knee with Stance Flexion and Extension Assist: L5812, L5845, L5850 base","manufacturer":"Otto_Bock_Knee","name":"3R93","lcode1":"L5812","lcode2":"L5845","lcode3":"L5850","lcode4":"L5925","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R93","cost":845.88,"reimbursement":2947.85,"percent":"29%","BestValue":"Ossur/Medi OFM2 & OMF2HD","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/3r93_image_1_.jpg"},
// {"category":"Safety Knee with Stance Flexion and Extension Assist: L5812, L5845, L5850 base","manufacturer":"Otto_Bock_Knee","name":"3R90","lcode1":"L5812","lcode2":"L5845","lcode3":"L5850","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R90","cost":967.67,"reimbursement":2500.75,"percent":"39%","BestValue":"Ossur/Medi OFM2 & OMF2HD","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/3R90_Image.jpg"},
//     ];

//     const kneeSix = [
// {"category":"Polycentric with Hydraulic Swing: L5814 base","manufacturer":"Otto_Bock_Knee","name":"3R60 Modular EBS Knee, includes 3R60 Pro","lcode1":"L5814","lcode2":"L5848","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R60","cost":2648.94,"reimbursement":4833.31,"percent":"55%","BestValue":"Otto Bock 3R60 Modular EBS/Pro","pdac":"No","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/3r60_image.jpg"},
// {"category":"Polycentric with Hydraulic Swing: L5814 base","manufacturer":"Legworks_Knee","name":"ATK Hydrapro HYD-PA-02","lcode1":"L5814","lcode2":"L5850","lcode3":"L5925","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"HYD-PA-02","cost":2067,"reimbursement":4322.87,"percent":"48%","BestValue":"Otto Bock 3R60 Modular EBS/Pro","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/hyd_pa_02_image_black_cover.jpg"},
// {"category":"Polycentric with Hydraulic Swing: L5814 base","manufacturer":"Otto_Bock_Knee","name":"3R67 Children’s Knee Joint","lcode1":"L5814","lcode2":" ","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R67","cost":1874.08,"reimbursement":3748.1,"percent":"50%","BestValue":"Otto Bock 3R60 Modular EBS/Pro","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/3R67_image_1a.jpg"},
// {"category":"Polycentric with Hydraulic Swing: L5814 base","manufacturer":"STG_Knee","name":"M0780","lcode1":"L5814","lcode2":"L5850","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"M0780","cost":1987.08,"reimbursement":3875.77,"percent":"51%","BestValue":"Otto Bock 3R60 Modular EBS/Pro","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/M0780_Image.jpg"},
// {"category":"Polycentric with Hydraulic Swing: L5814 base","manufacturer":"STG_Knee","name":"M0786","lcode1":"L5814","lcode2":"L5850","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"M0786","cost":2228.36,"reimbursement":3875.77,"percent":"57%","BestValue":"Otto Bock 3R60 Modular EBS/Pro","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/M0780_Image.jpg"},
//     ];

//     const kneeSeven = [
// {"category":"Polycentric with Hydraulic Swing & Stance Flexion: L5814, L5845 base","manufacturer":"Ossur_Medi_Knee","name":"Total Knee Unit Model 2000 (Hydraulic)","lcode1":"L5814","lcode2":"L5845","lcode3":"L5850","lcode4":"","lcode4":null,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"2000OSS","cost":1654.4,"reimbursement":5684.69,"percent":"29%","BestValue":"Ossur/Medi Total Knee Model 2000","pdac":"No","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/2000oss_image.jpg"},
// {"category":"Polycentric with Hydraulic Swing & Stance Flexion: L5814, L5845 base","manufacturer":"Ossur_Medi_Knee","name":"Medi Knee Model OH5SF","lcode1":"L5814","lcode2":"L5845","lcode3":"L5850","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"OH5SF","cost":1532.34,"reimbursement":5684.69,"percent":"27%","BestValue":"Ossur/Medi Total Knee Model 2000","pdac":"No","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/OH5SF_image.jpg"},
// {"category":"Polycentric with Hydraulic Swing & Stance Flexion: L5814, L5845 base","manufacturer":"STG_Knee","name":"M0782","lcode1":"L5814","lcode2":"L5845","lcode3":"L5850","lcode4":"L5925","lcode4":null,"lcode5":null,"lcode6":null,"lcode6":null,"hdcode":"M0782","cost":2096.26,"reimbursement":6131.79,"percent":"34%","BestValue":"Ossur/Medi Total Knee Model 2000","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/st_g_image_m0782_main.jpg"},
// {"category":"Polycentric with Hydraulic Swing & Stance Flexion: L5814, L5845 base","manufacturer":"STG_Knee","name":"M0787","lcode1":"L5814","lcode2":"L5845","lcode3":"L5850","lcode4":"L5925","lcode4":null,"lcode5":null,"lcode6":null,"lcode6":null,"hdcode":"M0787","cost":2337.54,"reimbursement":6131.79,"percent":"38%","BestValue":"Ossur/Medi Total Knee Model 2000","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/standg_image_m0787_main.jpg"},
// {"category":"Polycentric with Hydraulic Swing & Stance Flexion: L5814, L5845 base","manufacturer":"Legworks_Knee","name":"ATK HydraPro HYD-SF-02","lcode1":"L5814","lcode2":"L5845","lcode3":"L5850","lcode4":"L5925","lcode4": "" ,"lcode5":null,"lcode6":null,"lcode6": "" ,"hdcode":"HYD-SF-02","cost":2385,"reimbursement":6131.79,"percent":"39%","BestValue":"Ossur/Medi Total Knee Model 2000","pdac":"9/1/2019","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/legworks_image_hyd_sf_02_main.jpg"},
//     ];

//     const kneeEight = [
// {"category":"Polycentric with Hydraulic Swing, Stance Flexion, Extension Assist and High Activity Frame: L5814, L5845, L5850, L5930 base","manufacturer":"Proteor_Freedom_Knee","name":"Symphony N-6 Knee","lcode1":"L5814","lcode2":"L5845","lcode3":"L5850","lcode4":"L5930","lcode4":L5848,"lcode5":null,"lcode6":null,"lcode6": "" ,"hdcode":"NK6","cost":2358.13,"reimbursement":10166.81,"percent":"23%","BestValue":"Proteor Symphony N-6","pdac":"No","valuePer":75,"link":"","linkname":"",
//                                                                                                                                                                          "image":""},
// {"category":"Polycentric with Hydraulic Swing, Stance Flexion, Extension Assist and High Activity Frame: L5814, L5845, L5850, L5930 base","manufacturer":"Proteor_Freedom_Knee","name":"Symphony N-6+L Knee","lcode1":"L5814","lcode2":"L5845","lcode3":"L5850","lcode4":"L5930","lcode4":L5848,"lcode5":null,"lcode6":null,"lcode6": "" ,"hdcode":"8111-2700891-01","cost":2514.03,"reimbursement":10166.81,"percent":"25%","BestValue":"Proteor Symphony N-6","pdac":"No","valuePer":75,"link":"","linkname":"",
//                                                                                                                                                                         "image":""},
// {"category":"Polycentric with Hydraulic Swing, Stance Flexion, Extension Assist and High Activity Frame: L5814, L5845, L5850, L5930 base","manufacturer":"Ossur_Medi_Knee","name":"Medi Knee OH7","lcode1":"L5814","lcode2":"L5845","lcode3":"L5850","lcode4":"L5930","lcode4":null,"lcode5":null,"lcode6": "" ,"lcode6": "" ,"hdcode":"OH7-KNEE","cost":3161.82,"reimbursement":9081.6,"percent":"35%","BestValue":"Proteor Symphony N-6","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                                                         "image":""},
// {"category":"Polycentric with Hydraulic Swing, Stance Flexion, Extension Assist and High Activity Frame: L5814, L5845, L5850, L5930 base","manufacturer":"Ossur_Medi_Knee","name":"Total Knee Unit Model 2100 (High Activity Hydraulic)","lcode1":"L5814","lcode2":"L5845","lcode3":"L5850","lcode4":"L5930","lcode4":null,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"2100OSS","cost":3659.12,"reimbursement":9081.6,"percent":"40%","BestValue":"Proteor Symphony N-6","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                                                         "image":""},
//     ];

//     const kneeNine = [
// {"category":"Single Axis with Pneumatic Swing and Friction Stance: L5822, L5845 base","manufacturer":"Ossur_Medi_Knee","name":"Medi Knee Model OP4","lcode1":"L5822","lcode2":"L5845","lcode3":"L5850","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"OP4","cost":1067.95,"reimbursement":3636.05,"percent":"29%","BestValue":"Ossur/Medi Model OP4","pdac":"No","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/OP4_image.jpg"},
// {"category":"Single Axis with Pneumatic Swing and Friction Stance: L5822, L5845 base","manufacturer":"College_Park_Knee","name":"Victor","lcode1":"L5822","lcode2":"L5845","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"VPKA 200","cost":979.97,"reimbursement":3508.38,"percent":"28%","BestValue":"Ossur/Medi Model OP4","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/vpka_200_image_main.jpg"},
// {"category":"Single Axis with Pneumatic Swing and Friction Stance: L5822, L5845 base","manufacturer":"Otto_Bock_Knee","name":"3R92","lcode1":"L5822","lcode2":"L5845","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R92","cost":1380.55,"reimbursement":3508.38,"percent":"39%","BestValue":"Ossur/Medi Model OP4","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/3r92_image.jpg"},
//     ];

//     const kneeTen = [
// {"category":"Single Axis with Hydraulic Stance & Swing: L5828 base","manufacturer":"Otto_Bock_Knee","name":"3R80 Modular Rotary Hydraulic Knee Unit","lcode1":"L5828","lcode2":"L5845","lcode3":"L5850","lcode4":"L5925","lcode4":L5930,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R80","cost":2648.94,"reimbursement":8598.83,"percent":"31%","BestValue":"Otto Bock 3R80","pdac":"No","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/3r80_2_image.jpg"},
// {"category":"Single Axis with Hydraulic Stance & Swing: L5828 base","manufacturer":"Blatchford_Knee","name":"MH 30 Knee (Mercury High Activity Knee with 700 REX)","lcode1":"L5828","lcode2":"L5925","lcode3":"L5930","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"MERCURY-KIT","cost":1947.1,"reimbursement":6662.24,"percent":"29%","BestValue":"Otto Bock 3R80","pdac":"No","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/MERCURY_KNEE.jpg"},
// {"category":"Single Axis with Hydraulic Stance & Swing: L5828 base","manufacturer":"College_Park_Knee","name":"Capital","lcode1":"L5828","lcode2":"L5845","lcode3":"L5850","lcode4":"L5925","lcode4":null,"lcode5":null,"lcode6":null,"lcode6":null,"hdcode":"CHKA-KNEE","cost":1928.51,"reimbursement":5201.92,"percent":"37%","BestValue":"Otto Bock 3R80","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/chka_knee_image_main_pyramid.jpg"},
// {"category":"Single Axis with Hydraulic Stance & Swing: L5828 base","manufacturer":"Ossur_Medi_Knee","name":"Mauch Knee Standard","lcode1":"L5828","lcode2":"L5925","lcode3":"L5930","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"MKN71360","cost":2448.18,"reimbursement":6662.24,"percent":"37%","BestValue":"Otto Bock 3R80","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/mkn71360_image.jpg"},
// {"category":"Single Axis with Hydraulic Stance & Swing: L5828 base","manufacturer":"Ossur_Medi_Knee","name":"Mauch Knee Plus","lcode1":"L5828","lcode2":"L5925","lcode3":"L5930","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"MKN71660","cost":2741.58,"reimbursement":6662.24,"percent":"41%","BestValue":"Otto Bock 3R80","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/mkn01662_image_9.jpg"},
// {"category":"Single Axis with Hydraulic Stance & Swing: L5828 base","manufacturer":"Proteor_Freedom_Knee","name":"Hytrek","lcode1":"L5828","lcode2":"L5845","lcode3":"L5850","lcode4":"L5925","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"1P130","cost":2629.87,"reimbursement":5201.92,"percent":"51%","BestValue":"Otto Bock 3R80","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/1p130_knee_image_main.jpg"},
// {"category":"Single Axis with Hydraulic Stance & Swing: L5828 base","manufacturer":"Blatchford_Knee","name":"Hydraulic Swing & Stance Unit with Mercury Knee, single axis","lcode1":"L5828","lcode2":"L5925","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"MERCURY-SWING-KIT","cost":1947.1,"reimbursement":3265.33,"percent":"60%","BestValue":"Otto Bock 3R80","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/MERCURY_KNEE.jpg"},
//     ];

//     const kneeEleven = [
// {"category":"MicroProcessor : L5828 , L5848, L5848 base"  ,"manufacturer":"Blatchford_Knee","name":"Orion_MPK","lcode1":"L5828","lcode2":"L5845","lcode3":"L5848","lcode4":"L5856","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"ORION3-KIT","cost":13014.21,"reimbursement":29939.44,"percent":"43%","BestValue":"Blatchford Orion","pdac":"8/26/2020","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/1322AL_Image.jpg"},
// {"category":"MicroProcessor : L5828 , L5848, L5848 base"  ,"manufacturer":"Blatchford_Knee","name":"Linx","lcode1":"L5828","lcode2":"L5845","lcode3":"L5848","lcode4":"L5856","lcode4":L5973,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"LINX-KIT","cost":19898.31,"reimbursement":47302.67,"percent":"42%","BestValue":"Blatchford Orion","pdac":"9/18/2020","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/TK-4P0C.jpg"},
// {"category":"MicroProcessor : L5828 , L5848, L5848 base"  ,"manufacturer":"Otto_Bock_Knee","name":"C_Leg_MPK","lcode1":"L5828","lcode2":"L5845","lcode3":"L5848","lcode4":"L5856","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3C88/3C98-KIT","cost":12999,"reimbursement":29939.44,"percent":"43%","BestValue":"Blatchford Orion","pdac":"9/26/2016","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/TK-4P0C.jpg"},
// {"category":"MicroProcessor : L5828 , L5848, L5848 base"  ,"manufacturer":"Proteor_Freedom_Knee","name":"Plie MPK","lcode1":"L5828","lcode2":"L5845","lcode3":"L5848","lcode4":"L5850","lcode4":L5856,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"KS3/KD3-KNEE","cost":12800,"reimbursement":30067.11,"percent":"43%","BestValue":"Blatchford Orion","pdac":"4/19/2021","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/TK-4P0C.jpg"},
// {"category":"MicroProcessor : L5828 , L5848, L5848 base"  ,"manufacturer":"Ossur_Medi_Knee","name":"Rheo MPK","lcode1":"L5828","lcode2":"L5845","lcode3":"L5848","lcode4":"L5856","lcode4": "" ,"lcode5":  "NOTE: Additional codes - Not recommended unless additional clinical justification is provided.","lcode6":L5925,"lcode6":L5850,"hdcode":"RKN130003","cost":13162.2,"reimbursement":29939.44,"percent":"44%","BestValue":"Blatchford Orion","pdac":"4/1/2018","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/TK-4P0C.jpg"},
// {"category":"MicroProcessor : L5828 , L5848, L5848 base"  ,"manufacturer":"Proteor_Freedom_Knee","name":"Quattro MPK","lcode1":"L5828","lcode2":"L5845","lcode3":"L5848","lcode4":"L5850","lcode4":L5856,"lcode5":L5925,"lcode6":null,"lcode6":null,"hdcode":"QNX001-KNEE","cost":14370,"reimbursement":30514.21,"percent":"47%","BestValue":"Blatchford Orion","pdac":"4/22/2021","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/TK-4P0C.jpg"},
// {"category":"MicroProcessor : L5828 , L5848, L5848 base"  ,"manufacturer":"Otto_Bock_Knee","name":"Kenevo MPK","lcode1":"L5828","lcode2":"L5845","lcode3":"L5848","lcode4":"L5856","lcode4":null,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3C60-KIT","cost":14719,"reimbursement":29939.4,"percent":"49%","BestValue":"Blatchford Orion","pdac":"12/24/2020","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/TK-4P0C.jpg"},
// {"category":"MicroProcessor : L5828 , L5848, L5848 base"  ,"manufacturer":"Ossur_Medi_Knee","name":"Rheo XC MPK","lcode1":"L5828","lcode2":"L5845","lcode3":"L5848","lcode4":"L5856","lcode4": "" ,"lcode5":  "NOTE: Additional codes - Not recommended unless additional clinical justification is provided.","lcode6":L5925,"lcode6":L5850,"hdcode":"RKNXC0003","cost":20556,"reimbursement":29939.44,"percent":"69%","BestValue":"Blatchford Orion","pdac":"4/6/2018","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/TK-4P0C.jpg"},
// {"category":"MicroProcessor : L5828 , L5848, L5848 base"  ,"manufacturer":"Ossur_Medi_Knee","name":"Power Knee II MPK","lcode1":"L5828","lcode2":"L5845","lcode3":"L5848","lcode4":"L5856","lcode4":L5859,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"PKN120007","cost":33932.72,"reimbursement":44582.47,"percent":"76%","BestValue":"Blatchford Orion","pdac":"1/11/2018","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/TK-4P0C.jpg"},
// {"category":"MicroProcessor : L5828 , L5848, L5848 base"  ,"manufacturer":"Ossur_Medi_Knee","name":"Power Knee MPK","lcode1":"L5828","lcode2":"L5845","lcode3":"L5848","lcode4":"L5856","lcode4":L5859,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"PKN120007","cost":33932.72,"reimbursement":44582.47,"percent":"76%","BestValue":"Blatchford Orion","pdac":"1/11/2018","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/TK-4P0C.jpg"},
// {"category":"MicroProcessor : L5828 , L5848, L5848 base"  ,"manufacturer":"Otto_Bock_Knee","name":"3B1-2 Genium MPK (Now 3B1-3 OR 3B1-3=ST)","lcode1":"L5828","lcode2":"L5845","lcode3":"L5848","lcode4":"L5850","lcode4":L5930,"lcode5":"L5999-040","lcode6":"L5999-040","lcode6":"L5999-040","hdcode":"3B1","cost":31573.67,"reimbursement":"#N/A","percent":"#N/A","BestValue":"Blatchford Orion","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/TK-4P0C.jpg"},
//     ];

//     const kneeTwelve = [
// {"category":"Microprocessor - Swing Only: L5830 base"  ,"manufacturer":"Blatchford_Knee","name":"Smart Adaptive Knee with TT included","lcode1":"L5830","lcode2":"L5845","lcode3":"L5856","lcode4":"L5930","lcode4":L5984,"lcode5":L5988,"lcode6": "" ,"lcode6": "" ,"hdcode":"SMARTIP","cost":3777.41,"reimbursement":33911.23,"percent":"11%","BestValue":"Blatchford Smart Adaptive","pdac":"No","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/1322AL_Image.jpg"},
// {"category":"Microprocessor - Swing Only: L5830 base"  ,"manufacturer":"Blatchford_Knee","name":"Smart IP with stance flexion","lcode1":"L5830","lcode2":"L5845","lcode3":"L5857","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"SMARTIP","cost":3777.41,"reimbursement":12299.27,"percent":"31%","BestValue":"Blatchford Smart Adaptive","pdac":"8/28/2020","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/1322AL_Image.jpg"},
// {"category":"Microprocessor - Swing Only: L5830 base"  ,"manufacturer":"Blatchford_Knee","name":"Smart IP","lcode1":"L5830","lcode2":"L5857","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"SMARTIP","cost":3777.41,"reimbursement":10490.35,"percent":"36%","BestValue":"Blatchford Smart Adaptive","pdac":"8/28/2020","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/1322AL_Image.jpg"},
// {"category":"Microprocessor - Swing Only: L5830 base"  ,"manufacturer":"Blatchford_Knee","name":"Stance Flex ESK+ PSCP +MKL","lcode1":"L5830","lcode2":"L5845","lcode3":"L5850","lcode4":"L5925","lcode4":null,"lcode5":null,"lcode6":null,"lcode6":null,"hdcode":"ESK4BPPYR","cost":1838.38,"reimbursement":4277.39,"percent":"43%","BestValue":"Blatchford Smart Adaptive","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/1322AL_Image.jpg"},
// {"category":"Microprocessor - Swing Only: L5830 base"  ,"manufacturer":"Blatchford_Knee","name":"Stance Flex ESK+ PSCP (Pneumatic Swing)","lcode1":"L5830","lcode2":"L5845","lcode3":"","lcode4":"","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"ESK","cost":2039.72,"reimbursement":3702.62,"percent":"55%","BestValue":"Blatchford Smart Adaptive","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/1322AL_Image.jpg"},
//     ];

//     const kneeThirteen = [
// {"category": "Polycentric with Pneumatic Swing: L5840 base: L5830 base","manufacturer":"STG_Knee","name":"1322 (AL or AP)","lcode1":"L5840","lcode2":"L5850","lcode3":"","lcode4":"","lcode4":null,"lcode5":null,"lcode6":null,"lcode6":null,"hdcode":"1322A-KNEE","cost":586.55,"reimbursement":3629.13,"percent":"16%","BestValue":"STG 1322 (AL or AP)","pdac":"1/1/2014","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/1322AL_Image.jpg"},
// {"category":"Polycentric with Pneumatic Swing: L5840 base: L5830 base","manufacturer":"Otto_Bock_Knee","name":"3R78","lcode1":"L5840","lcode2":"L5850","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R78","cost":816.48,"reimbursement":3629.13,"percent":"22%","BestValue":"STG 1322 (AL or AP)","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/3R78-01-1200x1200.jpg"},
// {"category": "Polycentric with Pneumatic Swing: L5840 base: L5830 base","manufacturer":"Daw_Knee","name":"TK-4P0C","lcode1":"L5840","lcode2":"L5850","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"TK-4P0C","cost":947.03,"reimbursement":3629.13,"percent":"26%","BestValue":"STG 1322 (AL or AP)","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/TK-4P0C.jpg"},
// {"category": "Polycentric with Pneumatic Swing: L5840 base: L5830 base","manufacturer":"Otto_Bock_Knee","name":"3R106-PRO, PRO=ST, & PRO=KD","lcode1":"L5840","lcode2":"L5850","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R106","cost":1562.72,"reimbursement":3629.13,"percent":"43%","BestValue":"STG 1322 (AL or AP)","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":"../images/3r106_pro_image.jpg"},
//     ];

//     const kneeFourteen = [
// {"category":"Polycentric with Pneumatic Swing & Stance Flexion: L5840, L5845 base","manufacturer":"STG_Knee","name":"1323 AP knee, also known as S600","lcode1":"L5840","lcode2":"L5845","lcode3":"L5850","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"1323AP","cost":835.99,"reimbursement":5438.05,"percent":"15%","BestValue":"STG 1323 AP","pdac":"No","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Polycentric with Pneumatic Swing & Stance Flexion: L5840, L5845 base","manufacturer":"STG_Knee","name":"1323 AL knee, also known as S600","lcode1":"L5840","lcode2":"L5845","lcode3":"L5850","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"1323AL","cost":835.99,"reimbursement":5438.05,"percent":"15%","BestValue":"STG 1323 AP","pdac":"No","valuePer":75,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Polycentric with Pneumatic Swing & Stance Flexion: L5840, L5845 base","manufacturer":"Ossur_Medi_Knee","name":"Medi Knee Model OP5/OP5SF/KP5","lcode1":"L5840","lcode2":"L5845","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"OP5","cost":857.12,"reimbursement":5310.38,"percent":"16%","BestValue":"STG 1323 AP","pdac":"No","valuePer":35,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Polycentric with Pneumatic Swing & Stance Flexion: L5840, L5845 base","manufacturer":"Trulife_Knee","name":"SSK615","lcode1":"L5840","lcode2":"L5845","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"SSK615","cost":1207.76,"reimbursement":5310.38,"percent":"23%","BestValue":"STG 1323 AP","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Polycentric with Pneumatic Swing & Stance Flexion: L5840, L5845 base","manufacturer":"Ossur_Medi_Knee","name":"Medi Knee OHP3SF","lcode1":"L5840","lcode2":"L5845","lcode3":"L5850","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"OHP3SFHD","cost":1433.81,"reimbursement":5438.05,"percent":"26%","BestValue":"STG 1323 AP","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Polycentric with Pneumatic Swing & Stance Flexion: L5840, L5845 base","manufacturer":"Daw_Knee","name":"THK-4PSC","lcode1":"L5840","lcode2":"L5845","lcode3":"L5850","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"THK-4PSC","cost":2925.6,"reimbursement":5438.05,"percent":"54%","BestValue":"STG 1323 AP","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
//     ];

//     const kneeFifteen = [
// {"category":"Miscellaneous Knees","manufacturer":"Blatchford_Knee","name":"Stance Flex ESK With Programmable Knee Cylinder, Uniaxial Knee Attachment","lcode1":"L5616","lcode2":"L5857","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"ESK","cost":2039.72,"reimbursement":9955.16,"percent":"20%","BestValue":"No","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"Otto_Bock_Knee","name":"3R31 Prosedo","lcode1":"L5611","lcode2":"L5845","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R31","cost":742.95,"reimbursement":3416.84,"percent":"22%","BestValue":"No","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"STG_Knee","name":"L1321AL","lcode1":"L5818","lcode2":"L5850","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"L1321AL","cost":317.28,"reimbursement":1086.05,"percent":"29%","BestValue":"No","pdac":"1/20/2016","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"STG_Knee","name":"1318 S","lcode1":"L5810","lcode2":"L5850","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"1318S","cost":207.73,"reimbursement":613.55,"percent":"34%","BestValue":"No","pdac":"1/22/2014","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"Otto_Bock_Knee","name":"3R17 Single Axis Knee joint, lock","lcode1":"L5810","lcode2":"L5850","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R17","cost":265.57,"reimbursement":613.55,"percent":"43%","BestValue":"No","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"Otto_Bock_Knee","name":"3S80","lcode1":"L5824","lcode2":"L5850","lcode3":"L5925","lcode4":"L5930","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3S80","cost":2405.12,"reimbursement":5502.14,"percent":"44%","BestValue":"No","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"Proteor_Freedom_Knee","name":"Allux 4-bar MPK K3 Knee","lcode1":"K1014","lcode2":"L5845","lcode3":"L5848","lcode4":"L5856","lcode4": "" ,"lcode5": "" ,"lcode6":L5930,"lcode6":L7368,"hdcode":"NE-Z4","cost":14180.52,"reimbursement":null,"percent":"#N/A","BestValue":"No","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"STG_Knee","name":"L1311A","lcode1":"L5812","lcode2":"L5850","lcode3":"L5925","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"L1311A","cost":564.19,"reimbursement":1138.93,"percent":"50%","BestValue":"No","pdac":"4/29/2014","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"Otto_Bock_Knee","name":"3R95","lcode1":"L5826","lcode2":" ","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R95","cost":1687.83,"reimbursement":3151.66,"percent":"54%","BestValue":"No","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"Ossur_Medi_Knee","name":"Cheetah","lcode1":"L5613","lcode2":"L5930","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"CKN10000","cost":3226.64,"reimbursement":5910.84,"percent":"55%","BestValue":"No","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"Otto_Bock_Knee","name":"3R46","lcode1":"L5613","lcode2":"L5920","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R46","cost":1815.13,"reimbursement":3043.45,"percent":"60%","BestValue":"No","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"Otto_Bock_Knee","name":"3WR95","lcode1":"L5826","lcode2":"L5925","lcode3":"L5999","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3WR95","cost":2393.47,"reimbursement":3598.76,"percent":"67%","BestValue":"No","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"Aulie_Knee","name":"802 Prosthetic","lcode1":"L5824","lcode2":"L5850","lcode3":"L5925","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"802AUL","cost":1392.31,"reimbursement":2105.23,"percent":"66%","BestValue":"No","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"Otto_Bock_Knee","name":"3R55 Modular Polycentric","lcode1":"L5613","lcode2":" ","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3R55","cost":1813.17,"reimbursement":2513.93,"percent":"72%","BestValue":"No","pdac":"9/1/2017","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"Otto_Bock_Knee","name":"3P23","lcode1":"L5712","lcode2":"L5999","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3P23","cost":410.52,"reimbursement":437.07,"percent":"94%","BestValue":"No","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"Otto_Bock_Knee","name":"3B5 ‘X3’ MPK","lcode1":"L5999-052","lcode2":" ","lcode3":" ","lcode4":" ","lcode4": "" ,"lcode5": "" ,"lcode6": "" ,"lcode6": "" ,"hdcode":"3B5-KNEE","cost":42735.18,"reimbursement":null,"percent":"#N/A","BestValue":"No","pdac":"No","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"Blatchford_Knee","name":"KX06 Knee Unit (Hydraulic Swing and Stance Phase Control)","lcode1":"K1014","lcode2":"","lcode3":"","lcode4":"","lcode4":null,"lcode5":null,"lcode6":null,"lcode6":null,"hdcode":"KX06-KIT","cost":2206.68,"reimbursement":null,"percent":"#DIV/0!","BestValue":"No","pdac":"1/1/2011","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"Blatchford_Knee","name":"KX06 Knee Unit (Hydraulic Swing Control Only)","lcode1":"K1014","lcode2":"","lcode3":"","lcode4":"","lcode4":null,"lcode5":null,"lcode6":null,"lcode6":null,"hdcode":"KX06-KIT","cost":2206.68,"reimbursement":null,"percent":"#DIV/0!","BestValue":"No","pdac":"1/1/2011","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"Blatchford_Knee","name":"KX06 Polycentric Knee w/Swing and Stance Hydraulic","lcode1":"K1014","lcode2":"L5850","lcode3":"L5925","lcode4":"L5930","lcode4":null,"lcode5":null,"lcode6":null,"lcode6":null,"hdcode":"KX06-KIT","cost":2206.68,"reimbursement":null,"percent":"#DIV/0!","BestValue":"No","pdac":"1/1/2011","valuePer":10,"link":"","linkname":"",
//                                                                                                                                 "image":""},
// {"category":"Miscellaneous Knees","manufacturer":"Otto_Bock_Knee","name":"3R38","lcode1":"L5850","lcode2":"","lcode3":"","lcode4":"","lcode4":null,"lcode5":null,"lcode6":null,"lcode6":null,"hdcode":"3R38","cost":601.43,"reimbursement":127.67,"percent":"471%","BestValue":"No","pdac":"No","valuePer":10,"link":"","linkname":"","image":""}

//     ];

//     kneeOne;
//     kneeTwo;
//     kneeThree;
//     kneeFour;
//     kneeFive;
//     kneeSix;
//     kneeSeven;
//     kneeEight;
//     kneeNine;
//     kneeTen;
//     kneeEleven;
//     kneeTwelve;
//     kneeThirteen;
//     kneeFourteen;
//     kneeFifteen;
//     kneeSixteen;
// };


// export {kneeArray};
export {K14BFEA, kneeTwo};
